In [1]:
# Cell 2 — Imports

import json
from pathlib import Path

import chromadb
import pandas as pd

print("ChromaDB version:", chromadb.__version__)
print("Libraries imported successfully.")

ChromaDB version: 1.5.9
Libraries imported successfully.

In [2]:
# Cell 2 — Locate the cleaned product JSON

JSON_PATH = Path(r"C:\Users\Abhist\Desktop\KOHLER\DATA\kohler_ai_bathroom.products.json")

print("JSON path:")
print(JSON_PATH)

print("\nFile exists:", JSON_PATH.exists())

JSON path:
C:\Users\Abhist\Desktop\KOHLER\DATA\kohler_ai_bathroom.products.json

File exists: True

In [3]:
# Cell 4 — Load product data

with open(JSON_PATH, "r", encoding="utf-8") as f:
    products = json.load(f)

print("Number of products loaded:", len(products))
print("Data type:", type(products))

Number of products loaded: 36
Data type: <class 'list'>

In [4]:
# Cell 5 — Inspect one product

print(json.dumps(products[0], indent=4, ensure_ascii=False))

{
    "_id": {
        "$oid": "6aa96a2826ad3942f37da9fc"
    },
    "product_id": "1408991-IN4-A",
    "category": "Other",
    "collection": "Not specified",
    "color": [
        "White"
    ],
    "dimensions": {
        "width_mm": 344,
        "width_mm_available": true,
        "depth_mm": 483,
        "depth_mm_available": true,
        "height_mm": 141,
        "height_mm_available": true
    },
    "electrical": {
        "required": false,
        "required_source": "source",
        "voltage": "Not specified",
        "power_w": -1,
        "power_available": false
    },
    "extraction_method": "Groq text extraction",
    "extraction_status": "success",
    "features": [
        "Ergonomic and Straight line design suitable for compact rooms with deck space.",
        "Easy installation as it requires counter cutting to accommodate drain only.",
        "Optimum Depth to contain Splashes.",
        "Above counter without faucet deck.",
        "Only drain cutting (no profile cutting required).",
        "Without Overflow Hole"
    ],
    "installation": {
        "type": "Above Counter",
        "waste_outlet": "Not specified",
        "rough_in_mm": -1,
        "rough_in_available": false
    },
    "material": "Vitreous China",
    "product_name": "SPAN® Square Vessel Without Deck ( Small)",
    "source_pdf": "1408991-IN4.pdf",
    "source_type": "KOHLER specification PDF",
    "subcategory": "Not specified",
    "validation_problems": [
        "Missing category"
    ],
    "category_original": "Other",
    "subcategory_original": "Not specified",
    "installation_type": "Not specified",
    "waste_outlet": "Not specified",
    "voltage": "Not specified",
    "spatial_validation_possible": true,
    "data_quality": "complete_for_spatial_use"
}

In [5]:
# Cell 6 — Convert products into a DataFrame

df = pd.json_normalize(products)

print("Number of products:", len(df))
print("Number of fields:", len(df.columns))

display(df.head())

Number of products: 36
Number of fields: 36

,product_id,category,collection,color,extraction_method,extraction_status,features,material,product_name,source_pdf,...,dimensions.height_mm_available,electrical.required,electrical.required_source,electrical.voltage,electrical.power_w,electrical.power_available,installation.type,installation.waste_outlet,installation.rough_in_mm,installation.rough_in_available
0,1408991-IN4-A,Other,Not specified,[White],Groq text extraction,success,[Ergonomic and Straight line design suitable f...,Vitreous China,SPAN® Square Vessel Without Deck ( Small),1408991-IN4.pdf,...,True,False,source,Not specified,-1,False,Above Counter,Not specified,-1,False
1,29024IN-1,Vessel,Not specified,[White],Groq text extraction,success,"[Vitreous China, Circular Design, Without Over...",Vitreous China,CHALICE ROUND VESSEL 1TAP HOLE,29024IN-1_Chalice w deck vessel.pdf,...,True,False,source,Not specified,-1,False,Above counter,Not specified,-1,False
2,1311520-A04-D,BASINS / COUNTERTOP,Not specified,"[white, honed black]",Groq text extraction,success,"[Bench top installation, Slim vessel, CleanCoa...",Ceramic,Mica® Square 393mm Basin,90011T.pdf,...,False,False,source,Not specified,-1,False,Bench top installation,DN32 waste without overflow,50,True
3,K-12927IN,Other,Not specified,"[Polished Chrome, Vibrant® French Gold, Vibran...",Groq text extraction,success,[Designed to coordinate with a range of KOHLER...,Not specified,Complimentary™ Hygiene Spray,K-12927IN_spec_IN_Kohler_en.pdf,...,False,False,source,Not specified,-1,False,Wall-mount,Not specified,-1,False
4,K-1381T-S,Toilet,Veil,[White],Groq text extraction,success,[One-piece toilets integrate the tank and bowl...,Plastic seat,Veil™ One-piece elongated toilet with skirted ...,K-1381T-S_spec_IN_Kohler_en.pdf,...,True,False,source,Not specified,-1,False,Floor-mount,Floor,305,True

In [6]:
# Cell 7 — Display all fields

print("Available product fields:\n")

for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Available product fields:

1. product_id
2. category
3. collection
4. color
5. extraction_method
6. extraction_status
7. features
8. material
9. product_name
10. source_pdf
11. source_type
12. subcategory
13. validation_problems
14. category_original
15. subcategory_original
16. installation_type
17. waste_outlet
18. voltage
19. spatial_validation_possible
20. data_quality
21. _id.$oid
22. dimensions.width_mm
23. dimensions.width_mm_available
24. dimensions.depth_mm
25. dimensions.depth_mm_available
26. dimensions.height_mm
27. dimensions.height_mm_available
28. electrical.required
29. electrical.required_source
30. electrical.voltage
31. electrical.power_w
32. electrical.power_available
33. installation.type
34. installation.waste_outlet
35. installation.rough_in_mm
36. installation.rough_in_available

In [7]:
# Cell 8 — Inspect price and other important fields

important_keywords = [
    "price",
    "cost",
    "amount",
    "category",
    "subcategory",
    "dimensions",
    "installation",
    "electrical"
]

print("Fields potentially useful for structured retrieval:\n")

for column in df.columns:
    column_lower = column.lower()

    if any(keyword in column_lower for keyword in important_keywords):
        print(column)

Fields potentially useful for structured retrieval:

category
subcategory
category_original
subcategory_original
installation_type
dimensions.width_mm
dimensions.width_mm_available
dimensions.depth_mm
dimensions.depth_mm_available
dimensions.height_mm
dimensions.height_mm_available
electrical.required
electrical.required_source
electrical.voltage
electrical.power_w
electrical.power_available
installation.type
installation.waste_outlet
installation.rough_in_mm
installation.rough_in_available

In [8]:
# Cell 9 — Inspect important structured fields

fields_to_check = [
    "product_id",
    "category",
    "subcategory",
    "collection",
    "dimensions.width_mm",
    "dimensions.depth_mm",
    "dimensions.height_mm",
    "installation.type",
    "installation.rough_in_mm",
    "electrical.required",
    "electrical.voltage",
    "electrical.power_w"
]

for field in fields_to_check:
    if field in df.columns:
        print(f"\n===== {field} =====")
        print(df[field].head(10).to_string(index=False))

===== product_id =====
1408991-IN4-A
    29024IN-1
1311520-A04-D
    K-12927IN
    K-1381T-S
  K-17629T-NS
   K-17660T-M
     K-1851IN
     K-1853IN
    K-21226IN

===== category =====
              Other
             Vessel
BASINS / COUNTERTOP
              Other
             Toilet
             Toilet
        Toilet Seat
              Other
              Other
               Sink

===== subcategory =====
             Not specified
                    Vessel
          Countertop Basin
             Not specified
One-piece elongated toilet
          One-piece toilet
             Not specified
             Not specified
             Not specified
               Vessel sink

===== collection =====
  Not specified
  Not specified
  Not specified
  Not specified
           Veil
           Ove™
  Not specified
  Not specified
  Not specified
ModernLife Edge

===== dimensions.width_mm =====
344
470
393
 -1
 -1
 -1
 -1
 -1
 -1
600

===== dimensions.depth_mm =====
483
116
393
 -1
 -1
 -1
 -1
 -1
 -1
113

===== dimensions.height_mm =====
141
139
 -1
 -1
390
390
 -1
395
395
 -1

===== installation.type =====
         Above Counter
         Above counter
Bench top installation
            Wall-mount
           Floor-mount
           Floor-mount
         Not specified
           Floor-mount
           Floor-mount
                Vessel

===== installation.rough_in_mm =====
 -1
 -1
 50
 -1
305
185
 -1
180
220
 -1

===== electrical.required =====
False
False
False
False
False
False
False
False
False
False

===== electrical.voltage =====
Not specified
Not specified
Not specified
Not specified
Not specified
Not specified
Not specified
Not specified
Not specified
Not specified

===== electrical.power_w =====
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1

In [9]:
# Cell 10 — Structured retrieval dataset

retrieval_df = df.copy()

print("Structured retrieval dataset created.")
print("Products:", len(retrieval_df))
print("Fields:", len(retrieval_df.columns))

display(retrieval_df.head())

Structured retrieval dataset created.
Products: 36
Fields: 36

,product_id,category,collection,color,extraction_method,extraction_status,features,material,product_name,source_pdf,...,dimensions.height_mm_available,electrical.required,electrical.required_source,electrical.voltage,electrical.power_w,electrical.power_available,installation.type,installation.waste_outlet,installation.rough_in_mm,installation.rough_in_available
0,1408991-IN4-A,Other,Not specified,[White],Groq text extraction,success,[Ergonomic and Straight line design suitable f...,Vitreous China,SPAN® Square Vessel Without Deck ( Small),1408991-IN4.pdf,...,True,False,source,Not specified,-1,False,Above Counter,Not specified,-1,False
1,29024IN-1,Vessel,Not specified,[White],Groq text extraction,success,"[Vitreous China, Circular Design, Without Over...",Vitreous China,CHALICE ROUND VESSEL 1TAP HOLE,29024IN-1_Chalice w deck vessel.pdf,...,True,False,source,Not specified,-1,False,Above counter,Not specified,-1,False
2,1311520-A04-D,BASINS / COUNTERTOP,Not specified,"[white, honed black]",Groq text extraction,success,"[Bench top installation, Slim vessel, CleanCoa...",Ceramic,Mica® Square 393mm Basin,90011T.pdf,...,False,False,source,Not specified,-1,False,Bench top installation,DN32 waste without overflow,50,True
3,K-12927IN,Other,Not specified,"[Polished Chrome, Vibrant® French Gold, Vibran...",Groq text extraction,success,[Designed to coordinate with a range of KOHLER...,Not specified,Complimentary™ Hygiene Spray,K-12927IN_spec_IN_Kohler_en.pdf,...,False,False,source,Not specified,-1,False,Wall-mount,Not specified,-1,False
4,K-1381T-S,Toilet,Veil,[White],Groq text extraction,success,[One-piece toilets integrate the tank and bowl...,Plastic seat,Veil™ One-piece elongated toilet with skirted ...,K-1381T-S_spec_IN_Kohler_en.pdf,...,True,False,source,Not specified,-1,False,Floor-mount,Floor,305,True

In [10]:
# Cell 11 — Category distribution

if "category" in retrieval_df.columns:
    category_counts = (
        retrieval_df["category"]
        .fillna("Not specified")
        .value_counts()
    )

    print("Product categories:\n")
    display(category_counts)
else:
    print("Category field not found.")

Product categories:

category
Faucet                  14
Toilet                   5
Bathroom sink            5
Other                    4
Sink                     2
Vessel                   1
BASINS / COUNTERTOP      1
Toilet Seat              1
Bathroom Sink            1
Faucet Trim              1
Bathroom sink faucet     1
Name: count, dtype: int64

In [11]:
# Cell 13 — Normalize product categories

def normalize_category(category):
    """
    Converts inconsistent category names into a common
    category used by the retrieval system.
    
    The original category is NOT modified.
    """

    if not category:
        return "Other"

    value = str(category).strip().lower()

    # Toilets
    if "toilet seat" in value:
        return "Toilet Seat"

    if "toilet" in value:
        return "Toilet"

    # Faucets
    if "faucet" in value:
        return "Faucet"

    # Sinks / basins / vessels
    if (
        "sink" in value
        or "basin" in value
        or "vessel" in value
    ):
        return "Sink"

    # Showers
    if "shower" in value:
        return "Shower"

    # Vanity
    if "vanity" in value:
        return "Vanity"

    # Bathtub
    if (
        "bathtub" in value
        or "bath tub" in value
        or value == "bath"
    ):
        return "Bathtub"

    # Mirror
    if "mirror" in value:
        return "Mirror"

    return "Other"


retrieval_df["category_normalized"] = (
    retrieval_df["category"]
    .apply(normalize_category)
)

print("Normalized categories:")
display(
    retrieval_df["category_normalized"]
    .value_counts()
)

Normalized categories:

category_normalized
Faucet         16
Sink           10
Toilet          5
Other           4
Toilet Seat     1
Name: count, dtype: int64

In [12]:
# Cell 13 — Normalize product categories

def normalize_category(category):
    """
    Converts inconsistent category names into a common
    category used by the retrieval system.
    
    The original category is NOT modified.
    """

    if not category:
        return "Other"

    value = str(category).strip().lower()

    # Toilets
    if "toilet seat" in value:
        return "Toilet Seat"

    if "toilet" in value:
        return "Toilet"

    # Faucets
    if "faucet" in value:
        return "Faucet"

    # Sinks / basins / vessels
    if (
        "sink" in value
        or "basin" in value
        or "vessel" in value
    ):
        return "Sink"

    # Showers
    if "shower" in value:
        return "Shower"

    # Vanity
    if "vanity" in value:
        return "Vanity"

    # Bathtub
    if (
        "bathtub" in value
        or "bath tub" in value
        or value == "bath"
    ):
        return "Bathtub"

    # Mirror
    if "mirror" in value:
        return "Mirror"

    return "Other"


retrieval_df["category_normalized"] = (
    retrieval_df["category"]
    .apply(normalize_category)
)

print("Normalized categories:")
display(
    retrieval_df["category_normalized"]
    .value_counts()
)

Normalized categories:

category_normalized
Faucet         16
Sink           10
Toilet          5
Other           4
Toilet Seat     1
Name: count, dtype: int64

In [13]:
# Cell 14 — Verify category normalization

category_comparison = (
    retrieval_df[
        ["category", "category_normalized"]
    ]
    .drop_duplicates()
    .sort_values(
        ["category_normalized", "category"]
    )
)

display(category_comparison)

                category category_normalized
29  Bathroom sink faucet              Faucet
11                Faucet              Faucet
24           Faucet Trim              Faucet
0                  Other               Other
2    BASINS / COUNTERTOP                Sink
20         Bathroom Sink                Sink
14         Bathroom sink                Sink
9                   Sink                Sink
1                 Vessel                Sink
4                 Toilet              Toilet
6            Toilet Seat         Toilet Seat

In [14]:
# Cell 15 — Clean numeric fields

numeric_fields = [
    "dimensions.width_mm",
    "dimensions.depth_mm",
    "dimensions.height_mm",
    "dimensions.width_mm_available",
    "dimensions.depth_mm_available",
    "dimensions.height_mm_available",
    "electrical.power_w",
    "installation.rough_in_mm",
    "installation.rough_in_available"
]

for field in numeric_fields:
    if field in retrieval_df.columns:
        # Convert values to numeric where possible
        if not retrieval_df[field].dtype == bool:
            retrieval_df[field] = pd.to_numeric(
                retrieval_df[field],
                errors="coerce"
            )

# Replace -1 with missing
dimension_fields = [
    "dimensions.width_mm",
    "dimensions.depth_mm",
    "dimensions.height_mm",
    "electrical.power_w",
    "installation.rough_in_mm"
]

for field in dimension_fields:
    if field in retrieval_df.columns:
        retrieval_df.loc[
            retrieval_df[field] < 0,
            field
        ] = pd.NA

print("Numeric fields cleaned.")

Numeric fields cleaned.

In [15]:
# Cell 16 — Numeric constraint helper

def apply_max_constraint(
    dataframe,
    field,
    maximum
):
    """
    Applies a maximum-value constraint.

    Rules:
    1. Known value <= maximum  → PASS
    2. Known value > maximum   → REJECT
    3. Missing value            → KEEP for later validation

    Missing dimensions are not automatically rejected because
    they may be recoverable or may not have been specified
    in the product source.
    """

    if maximum is None:
        return dataframe

    if field not in dataframe.columns:
        return dataframe

    values = pd.to_numeric(
        dataframe[field],
        errors="coerce"
    )

    # Keep products when:
    # - the value is missing, OR
    # - the value satisfies the maximum constraint
    mask = values.isna() | (values <= maximum)

    return dataframe[mask]

In [16]:
# Cell 17 — Structured product retrieval

def filter_products(
    dataframe,
    category=None,
    max_width_mm=None,
    max_depth_mm=None,
    max_height_mm=None
):
    """
    Structured retrieval using hard product constraints.
    
    Parameters:
        category:
            Normalized product category.
        
        max_width_mm:
            Maximum acceptable product width.
        
        max_depth_mm:
            Maximum acceptable product depth.
        
        max_height_mm:
            Maximum acceptable product height.
    """

    result = dataframe.copy()

    # -----------------------------
    # Category filter
    # -----------------------------
    if category is not None:
        result = result[
            result["category_normalized"]
            .fillna("Other")
            .str.lower()
            == category.strip().lower()
        ]

    # -----------------------------
    # Width constraint
    # -----------------------------
    result = apply_max_constraint(
        result,
        "dimensions.width_mm",
        max_width_mm
    )

    # -----------------------------
    # Depth constraint
    # -----------------------------
    result = apply_max_constraint(
        result,
        "dimensions.depth_mm",
        max_depth_mm
    )

    # -----------------------------
    # Height constraint
    # -----------------------------
    result = apply_max_constraint(
        result,
        "dimensions.height_mm",
        max_height_mm
    )

    return result.reset_index(drop=True)

In [17]:
# Cell 12 — Basic structured filtering

def filter_by_category(dataframe, category=None):
    """
    Filter products using an exact category constraint.
    
    If category is None, all products are returned.
    """

    result = dataframe.copy()

    if category is not None:
        result = result[
            result["category"]
            .fillna("")
            .str.strip()
            .str.lower()
            == category.strip().lower()
        ]

    return result

In [18]:
# Test structured retrieval

results = filter_products(
    retrieval_df,
    category="Toilet",
    max_depth_mm=700
)

print("Products found:", len(results))

display(
    results[
        [
            "product_id",
            "product_name",
            "category",
            "category_normalized",
            "dimensions.width_mm",
            "dimensions.depth_mm",
            "dimensions.height_mm"
        ]
    ]
)

Products found: 5

,product_id,product_name,category,category_normalized,dimensions.width_mm,dimensions.depth_mm,dimensions.height_mm
0,K-1381T-S,Veil™ One-piece elongated toilet with skirted ...,Toilet,Toilet,NaN,NaN,390.0
1,K-17629T-NS,Ove™ One-piece round-front toilet with skirted...,Toilet,Toilet,NaN,NaN,390.0
2,K-28529IN,"Leap™ One-piece round-front smart toilet, dual...",Toilet,Toilet,NaN,NaN,400.0
3,K-33123IN-HC,KOHLER VIVE Hidden cord one-piece round-front ...,Toilet,Toilet,NaN,NaN,400.0
4,K-3983IN-S,Reach™ One-piece round-front toilet with skirt...,Toilet,Toilet,NaN,NaN,391.0

In [19]:
# Cell 18 — Installation type filter

def apply_installation_constraint(
    dataframe,
    installation_type=None
):
    """
    Filters products by installation type.

    Products with missing installation information are
    kept as candidates and can be validated later.
    """

    if installation_type is None:
        return dataframe

    if "installation.type" not in dataframe.columns:
        return dataframe

    values = (
        dataframe["installation.type"]
        .fillna("")
        .astype(str)
        .str.strip()
        .str.lower()
    )

    requested = installation_type.strip().lower()

    # Exact match OR unknown installation
    mask = (
        values.eq(requested)
        | values.eq("")
        | values.eq("not specified")
    )

    return dataframe[mask]

In [20]:
# Cell 19 — Rough-in constraint

def apply_rough_in_constraint(
    dataframe,
    required_rough_in_mm=None
):
    """
    Filters products based on rough-in.

    If rough-in is available, it must match the requested
    rough-in value.

    Products with unavailable rough-in are retained for
    later validation.
    """

    if required_rough_in_mm is None:
        return dataframe

    field = "installation.rough_in_mm"

    if field not in dataframe.columns:
        return dataframe

    values = pd.to_numeric(
        dataframe[field],
        errors="coerce"
    )

    # Allow a small tolerance because installation measurements
    # may have practical variation.
    tolerance = 10

    mask = (
        values.isna()
        | (
            (values - required_rough_in_mm).abs()
            <= tolerance
        )
    )

    return dataframe[mask]

In [21]:
# Cell 20 — Electrical requirement filter

def apply_electrical_constraint(
    dataframe,
    electrical_required=None
):
    """
    Filters products based on electrical requirements.

    If electrical requirement is unknown, the product is
    retained for later validation.
    """

    if electrical_required is None:
        return dataframe

    field = "electrical.required"

    if field not in dataframe.columns:
        return dataframe

    values = dataframe[field]

    # Convert common textual values to boolean
    normalized = (
        values.astype(str)
        .str.strip()
        .str.lower()
    )

    known_true = normalized.isin(
        ["true", "yes", "1"]
    )

    known_false = normalized.isin(
        ["false", "no", "0"]
    )

    # Unknown values
    unknown = ~(known_true | known_false)

    if electrical_required:
        mask = known_true | unknown
    else:
        mask = known_false | unknown

    return dataframe[mask]

In [22]:
# Cell 21 — Complete structured retrieval function

def filter_products(
    dataframe,
    category=None,
    max_width_mm=None,
    max_depth_mm=None,
    max_height_mm=None,
    installation_type=None,
    required_rough_in_mm=None,
    electrical_required=None
):
    """
    Main structured retrieval function.

    Applies hard product constraints using structured
    product metadata.
    """

    result = dataframe.copy()

    # -----------------------------
    # Category
    # -----------------------------
    if category is not None:
        result = result[
            result["category_normalized"]
            .fillna("Other")
            .str.lower()
            == category.strip().lower()
        ]

    # -----------------------------
    # Dimensions
    # -----------------------------
    result = apply_max_constraint(
        result,
        "dimensions.width_mm",
        max_width_mm
    )

    result = apply_max_constraint(
        result,
        "dimensions.depth_mm",
        max_depth_mm
    )

    result = apply_max_constraint(
        result,
        "dimensions.height_mm",
        max_height_mm
    )

    # -----------------------------
    # Installation
    # -----------------------------
    result = apply_installation_constraint(
        result,
        installation_type
    )

    # -----------------------------
    # Rough-in
    # -----------------------------
    result = apply_rough_in_constraint(
        result,
        required_rough_in_mm
    )

    # -----------------------------
    # Electrical
    # -----------------------------
    result = apply_electrical_constraint(
        result,
        electrical_required
    )

    return result.reset_index(drop=True)

In [23]:
# Cell 22 — Test multi-constraint retrieval

results = filter_products(
    retrieval_df,
    category="Toilet",
    max_depth_mm=700,
    max_height_mm=500,
    installation_type="Floor-mount",
    required_rough_in_mm=305
)

print("Products found:", len(results))

display(
    results[
        [
            "product_id",
            "product_name",
            "category_normalized",
            "dimensions.width_mm",
            "dimensions.depth_mm",
            "dimensions.height_mm",
            "installation.type",
            "installation.rough_in_mm",
            "electrical.required"
        ]
    ]
)

Products found: 3

,product_id,product_name,category_normalized,dimensions.width_mm,dimensions.depth_mm,dimensions.height_mm,installation.type,installation.rough_in_mm,electrical.required
0,K-1381T-S,Veil™ One-piece elongated toilet with skirted ...,Toilet,NaN,NaN,390.0,Floor-mount,305.0,False
1,K-28529IN,"Leap™ One-piece round-front smart toilet, dual...",Toilet,NaN,NaN,400.0,Floor-mount,305.0,True
2,K-3983IN-S,Reach™ One-piece round-front toilet with skirt...,Toilet,NaN,NaN,391.0,Floor-mount,305.0,False

In [25]:
# Cell 23 — Find price-related fields

price_keywords = [
    "price",
    "cost",
    "amount",
    "mrp",
    "inr",
    "rs",
    "₹"
]

price_fields = []

for column in retrieval_df.columns:
    column_lower = column.lower()

    if any(keyword in column_lower for keyword in price_keywords):
        price_fields.append(column)

print("Possible price-related fields:")

if price_fields:
    for field in price_fields:
        print("-", field)
else:
    print("No obvious price field found.")

Possible price-related fields:
No obvious price field found.

In [26]:
# Cell 24 — Search raw JSON recursively for price-related keys

def find_keys_containing(obj, keywords, path=""):
    """
    Recursively searches a JSON object for keys containing
    any of the supplied keywords.
    """

    found = []

    if isinstance(obj, dict):
        for key, value in obj.items():

            current_path = (
                f"{path}.{key}"
                if path
                else key
            )

            if any(
                keyword in key.lower()
                for keyword in keywords
            ):
                found.append(
                    (current_path, value)
                )

            found.extend(
                find_keys_containing(
                    value,
                    keywords,
                    current_path
                )
            )

    elif isinstance(obj, list):

        for index, item in enumerate(obj):

            current_path = f"{path}[{index}]"

            found.extend(
                find_keys_containing(
                    item,
                    keywords,
                    current_path
                )
            )

    return found


price_keys = find_keys_containing(
    products,
    ["price", "cost", "amount", "mrp"]
)

if price_keys:

    print("Price-related keys found:\n")

    for path, value in price_keys[:30]:
        print(path, "→", value)

else:
    print("No price-related keys found in the JSON.")

No price-related keys found in the JSON.

In [27]:
# Cell 25 — Create normalized price field

if "price" in retrieval_df.columns:

    retrieval_df["price_inr"] = pd.to_numeric(
        retrieval_df["price"],
        errors="coerce"
    )

elif "price_inr" in retrieval_df.columns:

    retrieval_df["price_inr"] = pd.to_numeric(
        retrieval_df["price_inr"],
        errors="coerce"
    )

else:

    # Price is currently unavailable
    retrieval_df["price_inr"] = pd.NA


print("Price field prepared.")

print(
    "Products with known price:",
    retrieval_df["price_inr"].notna().sum()
)

print(
    "Products without price:",
    retrieval_df["price_inr"].isna().sum()
)

Price field prepared.
Products with known price: 0
Products without price: 36

In [28]:
# Cell 26 — Budget constraint

def apply_budget_constraint(
    dataframe,
    max_price_inr=None
):
    """
    Filters products using maximum budget.

    Known prices above the budget are rejected.

    Products without a known price are retained and
    marked for later price validation.
    """

    if max_price_inr is None:
        return dataframe

    if "price_inr" not in dataframe.columns:
        return dataframe

    prices = pd.to_numeric(
        dataframe["price_inr"],
        errors="coerce"
    )

    # Keep:
    # 1. Products with known price <= budget
    # 2. Products whose price is unknown
    mask = (
        prices.isna()
        | (prices <= max_price_inr)
    )

    return dataframe[mask]

In [29]:
# Cell 27 — Updated structured retrieval function

def filter_products(
    dataframe,
    category=None,
    max_price_inr=None,
    max_width_mm=None,
    max_depth_mm=None,
    max_height_mm=None,
    installation_type=None,
    required_rough_in_mm=None,
    electrical_required=None
):
    """
    Main structured retrieval function.

    Uses exact product metadata for hard constraints.
    """

    result = dataframe.copy()

    # -----------------------------
    # Category
    # -----------------------------
    if category is not None:
        result = result[
            result["category_normalized"]
            .fillna("Other")
            .str.lower()
            == category.strip().lower()
        ]

    # -----------------------------
    # Budget
    # -----------------------------
    result = apply_budget_constraint(
        result,
        max_price_inr
    )

    # -----------------------------
    # Dimensions
    # -----------------------------
    result = apply_max_constraint(
        result,
        "dimensions.width_mm",
        max_width_mm
    )

    result = apply_max_constraint(
        result,
        "dimensions.depth_mm",
        max_depth_mm
    )

    result = apply_max_constraint(
        result,
        "dimensions.height_mm",
        max_height_mm
    )

    # -----------------------------
    # Installation
    # -----------------------------
    result = apply_installation_constraint(
        result,
        installation_type
    )

    # -----------------------------
    # Rough-in
    # -----------------------------
    result = apply_rough_in_constraint(
        result,
        required_rough_in_mm
    )

    # -----------------------------
    # Electrical
    # -----------------------------
    result = apply_electrical_constraint(
        result,
        electrical_required
    )

    return result.reset_index(drop=True)

In [30]:
# Test complete structured retrieval

results = filter_products(
    retrieval_df,
    category="Toilet",
    max_price_inr=80000,
    max_depth_mm=700,
    max_height_mm=500,
    installation_type="Floor-mount",
    required_rough_in_mm=305
)

print("Products found:", len(results))

display(
    results[
        [
            "product_id",
            "product_name",
            "category_normalized",
            "price_inr",
            "dimensions.width_mm",
            "dimensions.depth_mm",
            "dimensions.height_mm",
            "installation.type",
            "installation.rough_in_mm",
            "electrical.required"
        ]
    ]
)

Products found: 3

,product_id,product_name,category_normalized,price_inr,dimensions.width_mm,dimensions.depth_mm,dimensions.height_mm,installation.type,installation.rough_in_mm,electrical.required
0,K-1381T-S,Veil™ One-piece elongated toilet with skirted ...,Toilet,<NA>,NaN,NaN,390.0,Floor-mount,305.0,False
1,K-28529IN,"Leap™ One-piece round-front smart toilet, dual...",Toilet,<NA>,NaN,NaN,400.0,Floor-mount,305.0,True
2,K-3983IN-S,Reach™ One-piece round-front toilet with skirt...,Toilet,<NA>,NaN,NaN,391.0,Floor-mount,305.0,False

In [31]:
# Cell 28 — Constraint status helper

def check_max_value(value, maximum):
    """
    Checks whether a value satisfies a maximum constraint.

    Returns:
        True   -> constraint passed
        False  -> constraint failed
        None   -> value unavailable
    """

    if maximum is None:
        return True

    if pd.isna(value):
        return None

    return float(value) <= float(maximum)


def check_rough_in(value, required):
    """
    Checks rough-in compatibility with a 10 mm tolerance.
    """

    if required is None:
        return True

    if pd.isna(value):
        return None

    return abs(float(value) - float(required)) <= 10

In [32]:
# Cell 29 — Validate one product against requirements

def validate_product(
    product,
    max_price_inr=None,
    max_width_mm=None,
    max_depth_mm=None,
    max_height_mm=None,
    required_rough_in_mm=None,
    installation_type=None,
    electrical_required=None
):
    """
    Produces a detailed validation report for one product.
    """

    checks = {}

    # -----------------------------
    # Price
    # -----------------------------
    if max_price_inr is not None:
        price = product.get("price_inr")

        if pd.isna(price):
            checks["budget"] = None
        else:
            checks["budget"] = float(price) <= max_price_inr

    # -----------------------------
    # Width
    # -----------------------------
    checks["width"] = check_max_value(
        product.get("dimensions.width_mm"),
        max_width_mm
    )

    # -----------------------------
    # Depth
    # -----------------------------
    checks["depth"] = check_max_value(
        product.get("dimensions.depth_mm"),
        max_depth_mm
    )

    # -----------------------------
    # Height
    # -----------------------------
    checks["height"] = check_max_value(
        product.get("dimensions.height_mm"),
        max_height_mm
    )

    # -----------------------------
    # Rough-in
    # -----------------------------
    checks["rough_in"] = check_rough_in(
        product.get("installation.rough_in_mm"),
        required_rough_in_mm
    )

    # -----------------------------
    # Installation
    # -----------------------------
    if installation_type is not None:

        actual = str(
            product.get("installation.type", "")
        ).strip().lower()

        requested = installation_type.strip().lower()

        if actual in ["", "not specified", "none"]:
            checks["installation"] = None
        else:
            checks["installation"] = (
                actual == requested
            )

    # -----------------------------
    # Electrical
    # -----------------------------
    if electrical_required is not None:

        value = product.get(
            "electrical.required"
        )

        if pd.isna(value):
            checks["electrical"] = None
        else:
            checks["electrical"] = (
                bool(value)
                == bool(electrical_required)
            )

    return checks

In [33]:
# Cell 30 — Validation summary

def summarize_checks(checks):
    """
    Converts validation results into:
    
    PASS
    FAIL
    UNKNOWN
    """

    summary = {}

    for constraint, result in checks.items():

        if result is True:
            summary[constraint] = "PASS"

        elif result is False:
            summary[constraint] = "FAIL"

        else:
            summary[constraint] = "UNKNOWN"

    return summary

In [34]:
# Cell 31 — Test product validation

if len(retrieval_df) > 0:

    product = retrieval_df.iloc[0]

    checks = validate_product(
        product,
        max_depth_mm=700,
        max_height_mm=500,
        required_rough_in_mm=305,
        installation_type="Floor-mount"
    )

    summary = summarize_checks(checks)

    print("Product:")
    print(product["product_name"])

    print("\nValidation:")
    
    for constraint, status in summary.items():
        print(f"{constraint:15} → {status}")

Product:
SPAN® Square Vessel Without Deck ( Small)

Validation:
width           → PASS
depth           → PASS
height          → PASS
rough_in        → UNKNOWN
installation    → FAIL

In [35]:
# Cell 32 — Validation report for the catalog

def create_validation_report(
    dataframe,
    **requirements
):
    """
    Creates a validation report for every product.
    """

    reports = []

    for _, product in dataframe.iterrows():

        checks = validate_product(
            product,
            **requirements
        )

        summary = summarize_checks(checks)

        report = {
            "product_id": product.get("product_id"),
            "product_name": product.get("product_name"),
            "category": product.get("category_normalized"),
        }

        # Add validation statuses
        for constraint, status in summary.items():
            report[f"{constraint}_status"] = status

        reports.append(report)

    return pd.DataFrame(reports)

In [36]:
validation_report = create_validation_report(
    retrieval_df,
    max_depth_mm=700,
    max_height_mm=500,
    required_rough_in_mm=305,
    installation_type="Floor-mount"
)

display(validation_report.head(10))

,product_id,product_name,category,width_status,depth_status,height_status,rough_in_status,installation_status
0,1408991-IN4-A,SPAN® Square Vessel Without Deck ( Small),Other,PASS,PASS,PASS,UNKNOWN,FAIL
1,29024IN-1,CHALICE ROUND VESSEL 1TAP HOLE,Sink,PASS,PASS,PASS,UNKNOWN,FAIL
2,1311520-A04-D,Mica® Square 393mm Basin,Sink,PASS,PASS,UNKNOWN,FAIL,FAIL
3,K-12927IN,Complimentary™ Hygiene Spray,Other,PASS,UNKNOWN,UNKNOWN,UNKNOWN,FAIL
4,K-1381T-S,Veil™ One-piece elongated toilet with skirted ...,Toilet,PASS,UNKNOWN,PASS,PASS,PASS
5,K-17629T-NS,Ove™ One-piece round-front toilet with skirted...,Toilet,PASS,UNKNOWN,PASS,FAIL,PASS
6,K-17660T-M,Ove™ Quiet-Close™ elongated toilet seat,Toilet Seat,PASS,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
7,K-1851IN,Brive Plus,Other,PASS,UNKNOWN,PASS,FAIL,PASS
8,K-1853IN,Brive Plus,Other,PASS,UNKNOWN,PASS,FAIL,PASS
9,K-21226IN,ModernLife Edge 600 mm rectangular vessel bath...,Sink,PASS,PASS,UNKNOWN,UNKNOWN,FAIL

In [40]:
from pathlib import Path
import chromadb

CHROMA_PATH = Path(
    r"C:\Users\Abhist\Desktop\KOHLER\data\chroma_db"
)

CHROMA_PATH.mkdir(
    parents=True,
    exist_ok=True
)

chroma_client = chromadb.PersistentClient(
    path=str(CHROMA_PATH)
)

print("ChromaDB initialized successfully.")
print("Database path:", CHROMA_PATH)

ChromaDB initialized successfully.
Database path: C:\Users\Abhist\Desktop\KOHLER\data\chroma_db

In [38]:
from chromadb.utils.embedding_functions import DefaultEmbeddingFunction

embedding_function = DefaultEmbeddingFunction()

print("Default embedding function created successfully.")

Default embedding function created successfully.

In [39]:
test_text = "Japanese Zen minimalist bathroom faucet"

test_embedding = embedding_function([test_text])

print("Embedding generated successfully.")
print("Embedding type:", type(test_embedding))
print("Number of embeddings:", len(test_embedding))

if len(test_embedding) > 0:
    print("Embedding dimension:", len(test_embedding[0]))

C:\Users\Abhist\.cache\chroma\onnx_models\all-MiniLM-L6-v2\onnx.tar.gz: 100%|██████████| 79.3M/79.3M [00:17<00:00, 4.66MiB/s]

Embedding generated successfully.
Embedding type: <class 'list'>
Number of embeddings: 1
Embedding dimension: 384

In [41]:
collection = chroma_client.get_or_create_collection(
    name="kohler_products",
    embedding_function=embedding_function,
    metadata={
        "description": "KOHLER bathroom product semantic retrieval"
    }
)

print("Collection created successfully.")
print("Collection name:", collection.name)

Collection created successfully.
Collection name: kohler_products

In [44]:
def clean_metadata_value(value):
    """
    Convert values into formats that ChromaDB can safely
    store as metadata.
    """

    # Handle None
    if value is None:
        return "Not specified"

    # Handle pandas missing values
    if pd.isna(value):
        return "Not specified"

    # Handle lists such as features and colors
    if isinstance(value, list):
        return ", ".join(str(x) for x in value)

    return value


# Prepare data for ChromaDB

chroma_ids = []
chroma_documents = []
chroma_metadatas = []

for _, product in retrieval_df.iterrows():

    product_id = str(product["product_id"])

    metadata = {
        "product_id": product_id,

        "product_name": clean_metadata_value(
            product.get("product_name")
        ),

        "category": clean_metadata_value(
            product.get("category_normalized")
        ),

        "collection": clean_metadata_value(
            product.get("collection")
        ),

        "material": clean_metadata_value(
            product.get("material")
        ),

        "color": clean_metadata_value(
            product.get("color")
        ),

        "installation_type": clean_metadata_value(
            product.get("installation.type")
        )
    }

    chroma_ids.append(product_id)

    chroma_documents.append(
        product["semantic_text"]
    )

    chroma_metadatas.append(metadata)


print("ChromaDB data prepared successfully.")
print("IDs:", len(chroma_ids))
print("Documents:", len(chroma_documents))
print("Metadata:", len(chroma_metadatas))

KeyError: 'semantic_text'

In [42]:
collection.upsert(
    ids=chroma_ids,
    documents=chroma_documents,
    metadatas=chroma_metadatas
)

print("Products added to ChromaDB.")
print("Number of records:", collection.count())

NameError: name 'chroma_ids' is not defined