In [1]:
import os
import json
from pathlib import Path

import pandas as pd
from pymongo import MongoClient
from dotenv import load_dotenv

In [2]:
MONGO_URI = "mongodb://localhost:27017"

try:
    mongo_client = MongoClient(
        MONGO_URI,
        serverSelectionTimeoutMS=5000
    )

    mongo_client.admin.command("ping")

    db = mongo_client["kohler_ai_bathroom"]
    products_collection = db["products"]

    print("✓ MongoDB connected successfully.")
    print("Database:", db.name)
    print("Collection:", products_collection.name)

except Exception as e:
    raise ConnectionError(
        "Could not connect to MongoDB. "
        "Make sure MongoDB is running."
    ) from e

✓ MongoDB connected successfully.
Database: kohler_ai_bathroom
Collection: products

In [3]:
total_products = products_collection.count_documents({})

print("Total products in MongoDB:", total_products)

Total products in MongoDB: 36

In [4]:
products = list(
    products_collection.find(
        {},
        {"_id": 0}
    )
)

print(f"Loaded {len(products)} products.")

Loaded 36 products.

In [5]:
df = pd.DataFrame(products)

print("Dataset shape:", df.shape)

df.head()

Dataset shape: (36, 23)

,product_id,category,collection,color,dimensions,electrical,extraction_method,extraction_status,features,installation,...,source_type,subcategory,validation_problems,category_original,subcategory_original,installation_type,waste_outlet,voltage,spatial_validation_possible,data_quality
0,1408991-IN4-A,Other,Not specified,[White],"{'width_mm': 344.0, 'width_mm_available': True...","{'required': False, 'required_source': 'inferr...",Groq text extraction,success,[Ergonomic and Straight line design suitable f...,"{'type': 'Above Counter', 'waste_outlet': 'Not...",...,KOHLER specification PDF,Not specified,[Missing category],NaN,NaN,Not specified,Not specified,Not specified,True,complete_for_spatial_use
1,29024IN-1,Vessel,Not specified,[White],"{'width_mm': 470.0, 'width_mm_available': True...","{'required': False, 'required_source': 'inferr...",Groq text extraction,success,"[Vitreous China, Circular Design, Without Over...","{'type': 'Above counter', 'waste_outlet': 'Not...",...,KOHLER specification PDF,Vessel,[],Vessel,Vessel,Not specified,Not specified,Not specified,True,complete_for_spatial_use
2,1311520-A04-D,BASINS / COUNTERTOP,Not specified,"[white, honed black]","{'width_mm': 393.0, 'width_mm_available': True...","{'required': False, 'required_source': 'inferr...",Groq text extraction,success,"[Bench top installation, Slim vessel, CleanCoa...","{'type': 'Bench top installation', 'waste_outl...",...,KOHLER specification PDF,Countertop Basin,[Missing height],BASINS / COUNTERTOP,Countertop Basin,Not specified,Not specified,Not specified,False,complete_with_unspecified_source_fields
3,K-12927IN,Other,Not specified,"[Polished Chrome, Vibrant® French Gold, Vibran...","{'width_mm': -1.0, 'width_mm_available': False...","{'required': False, 'required_source': 'inferr...",Groq text extraction,success,[Designed to coordinate with a range of KOHLER...,"{'type': 'Wall-mount', 'waste_outlet': 'Not sp...",...,KOHLER specification PDF,Not specified,"[Missing category, Missing width, Missing dept...",NaN,NaN,Not specified,Not specified,Not specified,False,complete_with_unspecified_source_fields
4,K-1381T-S,Toilet,Veil,[White],"{'width_mm': -1.0, 'width_mm_available': False...","{'required': False, 'required_source': 'inferr...",Groq text extraction,success,[One-piece toilets integrate the tank and bowl...,"{'type': 'Floor-mount', 'waste_outlet': 'Floor...",...,KOHLER specification PDF,One-piece elongated toilet,"[Missing width, Missing depth]",Toilet,One-piece elongated toilet,Not specified,Not specified,Not specified,False,complete_with_unspecified_source_fields

In [6]:
all_fields = set()

for product in products:
    all_fields.update(product.keys())

print("Fields found in the dataset:\n")

for field in sorted(all_fields):
    print("-", field)

Fields found in the dataset:

- category
- category_original
- collection
- color
- data_quality
- dimensions
- electrical
- extraction_method
- extraction_status
- features
- installation
- installation_type
- material
- product_id
- product_name
- source_pdf
- source_type
- spatial_validation_possible
- subcategory
- subcategory_original
- validation_problems
- voltage
- waste_outlet

In [7]:
def get_nested_value(product, parent, child):
    value = product.get(parent)

    if isinstance(value, dict):
        return value.get(child)

    return None

In [8]:
inspection_data = []

for product in products:

    inspection_data.append({
        "product_id": product.get("product_id"),
        "product_name": product.get("product_name"),
        "category": product.get("category"),
        "subcategory": product.get("subcategory"),
        "collection": product.get("collection"),

        "width_mm": get_nested_value(
            product, "dimensions", "width_mm"
        ),

        "depth_mm": get_nested_value(
            product, "dimensions", "depth_mm"
        ),

        "height_mm": get_nested_value(
            product, "dimensions", "height_mm"
        ),

        "rough_in_mm": get_nested_value(
            product, "installation", "rough_in_mm"
        ),

        "installation_type": get_nested_value(
            product, "installation", "type"
        ),

        "waste_outlet": get_nested_value(
            product, "installation", "waste_outlet"
        ),

        "electrical_required": get_nested_value(
            product, "electrical", "required"
        ),

        "voltage": get_nested_value(
            product, "electrical", "voltage"
        ),

        "power_w": get_nested_value(
            product, "electrical", "power_w"
        ),

        "material": product.get("material"),
        "color": product.get("color"),
        "features": product.get("features")
    })

inspection_df = pd.DataFrame(inspection_data)

display(inspection_df)

,product_id,product_name,category,subcategory,collection,width_mm,depth_mm,height_mm,rough_in_mm,installation_type,waste_outlet,electrical_required,voltage,power_w,material,color,features
0,1408991-IN4-A,SPAN® Square Vessel Without Deck ( Small),Other,Not specified,Not specified,344.0,483.0,141.0,-1.0,Above Counter,Not specified,False,Not specified,-1.0,Vitreous China,[White],[Ergonomic and Straight line design suitable f...
1,29024IN-1,CHALICE ROUND VESSEL 1TAP HOLE,Vessel,Vessel,Not specified,470.0,116.0,139.0,-1.0,Above counter,Not specified,False,Not specified,-1.0,Vitreous China,[White],"[Vitreous China, Circular Design, Without Over..."
2,1311520-A04-D,Mica® Square 393mm Basin,BASINS / COUNTERTOP,Countertop Basin,Not specified,393.0,393.0,-1.0,50.0,Bench top installation,DN32 waste without overflow,False,Not specified,-1.0,Ceramic,"[white, honed black]","[Bench top installation, Slim vessel, CleanCoa..."
3,K-12927IN,Complimentary™ Hygiene Spray,Other,Not specified,Not specified,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Not specified,"[Polished Chrome, Vibrant® French Gold, Vibran...",[Designed to coordinate with a range of KOHLER...
4,K-1381T-S,Veil™ One-piece elongated toilet with skirted ...,Toilet,One-piece elongated toilet,Veil,-1.0,-1.0,390.0,305.0,Floor-mount,Floor,False,Not specified,-1.0,Plastic seat,[White],[One-piece toilets integrate the tank and bowl...
5,K-17629T-NS,Ove™ One-piece round-front toilet with skirted...,Toilet,One-piece toilet,Ove™,-1.0,-1.0,390.0,185.0,Floor-mount,Floor,False,Not specified,-1.0,Not specified,[White],[One-piece toilets integrate the tank and bowl...
6,K-17660T-M,Ove™ Quiet-Close™ elongated toilet seat,Toilet Seat,Not specified,Not specified,-1.0,-1.0,-1.0,-1.0,Not specified,Not specified,False,Not specified,-1.0,Plastic construction,[White],"[Elongated closed-front seat with lid, Quiet-C..."
7,K-1851IN,Brive Plus,Other,Not specified,Not specified,-1.0,-1.0,395.0,180.0,Floor-mount,Floor,False,Not specified,-1.0,Not specified,[White],[Round-front bowl offers an ideal solution for...
8,K-1853IN,Brive Plus,Other,Not specified,Not specified,-1.0,-1.0,395.0,220.0,Floor-mount,Floor,False,Not specified,-1.0,Not specified,[White],"[Elongated bowl offers added room and comfort,..."
9,K-21226IN,ModernLife Edge 600 mm rectangular vessel bath...,Sink,Vessel sink,ModernLife Edge,600.0,113.0,-1.0,-1.0,Vessel,Not specified,False,Not specified,-1.0,Vitreous china,"[Honed Black, Thunder grey, Honed Peacock, Hon...","[Contemporary design makes a modern statement,..."
10,K-2200IN,Conical Bell™,Sink,Vessel sink,Not specified,413.0,-1.0,-1.0,464.0,Semi-recessed vessel,"Center drain, no overflow",False,Not specified,-1.0,Vitreous china,"[White, Cashmere, Black]","[Traditional design creates a classic look, Ro..."
11,K-23486IN-4ND,"Parallel™ Wall-mount bathroom sink faucet, 9.0...",Faucet,Wall-mount bathroom sink faucet,Parallel,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium metal,"[Polished Chrome, Vibrant French Gold, Vibrant...",[Single handle controls both on/off activation...
12,K-23966IN-4ND,KOHLER VIVE® Single-handle bathroom sink fauce...,Faucet,Single-handle bathroom sink faucet,Not specified,-1.0,-1.0,-1.0,-1.0,Single hole,Not specified,False,Not specified,-1.0,Premium metal construction,"[Polished Chrome, Vibrant® French Gold, Matte ...",[Single handle controls both on/off activation...
13,K-23967IN-4ND,KOHLER VIVE® Tall single-handle bathroom sink ...,Faucet,Tall single-handle bathroom sink faucet,VIVE,-1.0,-1.0,-1.0,-1.0,Single hole,Drain sold separately,False,Not specified,-1.0,Premium metal construction,"[Polished Chrome, Vibrant® French Gold, Matte ...",[Single handle controls both on/off activation...
14,K-25316IN,Span™ 537 mm rectangular vessel bathroom sink ...,Bathroom sink,Vessel sink,Not specified,537.0,-1.0,-1.0,-1.0,Vessel,Not specified,False,Not specified,-1.0,Vitreous china,[White],"[Minimalist design with thin, rounded edges, R..."
15,K-2661IN,Vox™ 413 mm square vessel bathroom sink,Bathroom sink,Vessel,Vox™,413.0,413.0,-1.0,-1.0,Semi-recessed vessel,Not specified,False,Not specified,-1.0,Vitreous china,"[White, Black]",[Deep square basin with a contemporary design ...
16,K-27477IN-4ND,"Fore Tri® Single-handle bathroom sink faucet, ...",Faucet,Single-handle bathroom sink faucet,Not specified,-1.0,-1.0,-1.0,-1.0,Deck-mount,Not specified,False,Not specified,-1.0,Premium material,[Polished Chrome],"[Sleek and contemporary design, Single handle ..."
17,K-27480IN-4ND,Fore Line™ Tall single-handle bathroom sink fa...,Faucet,Bathroom sink faucet,Fore Line™,-1.0,-1.0,-1.0,-1.0,Deck-mount,Not specified,False,Not specified,-1.0,Premium material,"[Polished Chrome, Vibrant® French Gold]","[Single handle provides on/off activation, vol..."
18,K-27485IN-4,"Fore Line™ Single-handle bathroom sink faucet,...",Faucet,Not specified,Fore Line™,-1.0,96.0,86.0,-1.0,"Deck-mount, single-hole installation",Not specified,False,Not specified,-1.0,Premium metal construction,"[Polished Chrome, Vibrant® French Gold]","[For use with cold water line only, Single han..."
19,K-28529IN,"Leap™ One-piece round-front smart toilet, dual...",Toilet,One-piece round-front smart toilet,Not specified,-1.0,-1.0,400.0,305.0,Floor-mount,Floor,True,220-240 V,1200.0,Plastic seat,[White],[One-piece toilets integrate the tank and bowl...
20,K-28784IN,KOHLER VIVE® 552 mm rectangular vessel bathroo...,Bathroom Sink,Vessel,Not specified,-1.0,-1.0,-1.0,-1.0,Semi-recessed vessel,Not specified,False,Not specified,-1.0,Vitreous china,"[White, Cashmere, Black, Indigo Gloss, Teak Be...","[Rectangular basin with rounded corners, Sleek..."
21,K-33123IN-HC,KOHLER VIVE Hidden cord one-piece round-front ...,Toilet,Not specified,Vive,-1.0,-1.0,400.0,220.0,Floor-mount,Floor,False,Not specified,-1.0,Not specified,[White],[One-piece toilets integrate the tank and bowl...
22,K-3983IN-S,Reach™ One-piece round-front toilet with skirt...,Toilet,One-piece round-front toilet,Reach™,-1.0,-1.0,391.0,305.0,Floor-mount,Floor,False,Not specified,-1.0,Plastic seat,[White],[One-piece toilets integrate the tank and bowl...
23,K-5373IN,Forefront™ 580 mm rectangular vessel bathroom ...,Bathroom sink,Vessel,Forefront™,-1.0,-1.0,-1.0,-1.0,Semi-recessed vessel,Not specified,False,Not specified,-1.0,Vitreous china,"[White, Cashmere, Black]",[Deep rectangular basin with a contemporary de...
24,K-5684IN-4ND,"Aleo+™ Wall-mount bathroom sink faucet trim, 9...",Faucet Trim,Wall-mount bathroom sink faucet trim,Aleo+,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium material construction,"[Polished Chrome, Vibrant® French Gold, Vibran...","[Sleek contemporary design, Single Lever handl..."
25,K-72298IN-4ND,"Aleo® Tall single-handle bathroom sink faucet,...",Faucet,Bathroom sink faucet,Aleo™,-1.0,-1.0,-1.0,-1.0,single-hole,Not specified,False,Not specified,-1.0,Premium metal,"[Polished Chrome, Vibrant® Brushed Bronze, Vib...","[Tall height is ideal for vessel-style sinks, ..."
26,K-72337IN-4ND,Aleo+™ Tall single-handle bathroom sink faucet...,Faucet,Bathroom sink faucet,Aleo+,-1.0,-1.0,-1.0,-1.0,Deck-mount,Not specified,False,Not specified,-1.0,Premium metal,"[Polished Chrome, Vibrant® French Gold, Vibran...","[Tall height is ideal for vessel-style sinks, ..."
27,K-75374IN-1,Forefront™ 460 mm square vessel bathroom sink ...,Bathroom sink,Vessel sink,Forefront™,460.0,460.0,-1.0,-1.0,Semi-recessed vessel,Not specified,False,Not specified,-1.0,Vitreous china,[White],"[Contemporary design makes a modern statement,..."
28,K-75375IN,Forefront™ 890 mm rectangular vessel bathroom ...,Bathroom sink,Vessel sink,Forefront™,-1.0,-1.0,120.0,-1.0,Vessel,Not specified,False,Not specified,-1.0,Vitreous china,[White],"[Contemporary design makes a modern statement,..."
29,K-75377IN-4,"July™ Single-handle bathroom sink faucet, cold...",Bathroom sink faucet,Not specified,July™,-1.0,-1.0,-1.0,-1.0,"Single-hole, Deck-mount",Not specified,False,Not specified,-1.0,Premium material,"[Polished Chrome, Vibrant® French Gold, Vibran...","[Versatile modern design, Single Lever handle ..."
30,K-77364IN,"Health faucet, 8.5 lpm",Faucet,Not specified,Luxe™,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Antimicrobial silicone,[Polished Chrome],"[Ergonomic, easy clean design, Optimized spray..."
31,K-97258IN-ZZ,"Elate™ Single-function health faucet, 8.5 lpm",Faucet,Health faucet,Not specified,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium material construction for durability a...,"[Vibrant® French Gold, Vibrant® Brushed Bronze...",[Single-function hygiene spray delivers a full...
32,K-97258IN,"Elate™ Single-function health faucet, 8.5 lpm",Faucet,Not specified,Not specified,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium material construction for durability a...,"[Polished Chrome, Matte Black]",[Single-function hygiene spray delivers a full...
33,K-97347T-4,Avid™ Tall Single-handle bathroom sink faucet,Faucet,Single-handle,Avid™ Tall,-1.0,-1.0,-1.0,-1.0,Not specified,Not specified,False,Not specified,-1.0,Brass,[Polished Chrome],[KOHLER ceramic disc valves exceed industry lo...
34,K-98100IN-ZZ,"Beam™ Health faucet, 10 lpm",Faucet,Health faucet,Not specified,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium material,[Matte Black],"[Contemporary styling matches any decor, Easy ..."
35,K-98100IN,"Cuff™ Single-function health faucet, 11.5 lpm",Faucet,Health faucet,Not specified,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium material construction,"[Polished Chrome, White]","[Contemporary styling matches any decor, Easy ..."

In [9]:
missing_counts = inspection_df.isna().sum()

missing_percentage = (
    inspection_df.isna().mean() * 100
).round(2)

missing_report = pd.DataFrame({
    "missing_count": missing_counts,
    "missing_percentage": missing_percentage
})

display(
    missing_report.sort_values(
        "missing_count",
        ascending=False
    )
)

                     missing_count  missing_percentage
product_id                       0                 0.0
product_name                     0                 0.0
category                         0                 0.0
subcategory                      0                 0.0
collection                       0                 0.0
width_mm                         0                 0.0
depth_mm                         0                 0.0
height_mm                        0                 0.0
rough_in_mm                      0                 0.0
installation_type                0                 0.0
waste_outlet                     0                 0.0
electrical_required              0                 0.0
voltage                          0                 0.0
power_w                          0                 0.0
material                         0                 0.0
color                            0                 0.0
features                         0                 0.0

In [10]:
missing_product_ids = inspection_df[
    inspection_df["product_id"].isna()
    | (inspection_df["product_id"].astype(str).str.strip() == "")
]

print(
    "Products with missing product_id:",
    len(missing_product_ids)
)

display(missing_product_ids)

Products with missing product_id: 0

Empty DataFrame
Columns: [product_id, product_name, category, subcategory, collection, width_mm, depth_mm, height_mm, rough_in_mm, installation_type, waste_outlet, electrical_required, voltage, power_w, material, color, features]
Index: []

In [11]:
duplicate_ids = inspection_df[
    inspection_df["product_id"].duplicated(
        keep=False
    )
]

print(
    "Products involved in duplicate product IDs:",
    len(duplicate_ids)
)

display(
    duplicate_ids.sort_values("product_id")
)

Products involved in duplicate product IDs: 0

Empty DataFrame
Columns: [product_id, product_name, category, subcategory, collection, width_mm, depth_mm, height_mm, rough_in_mm, installation_type, waste_outlet, electrical_required, voltage, power_w, material, color, features]
Index: []

In [12]:
missing_names = inspection_df[
    inspection_df["product_name"].isna()
    | (inspection_df["product_name"].astype(str).str.strip() == "")
]

print(
    "Products with missing product_name:",
    len(missing_names)
)

display(missing_names)

Products with missing product_name: 0

Empty DataFrame
Columns: [product_id, product_name, category, subcategory, collection, width_mm, depth_mm, height_mm, rough_in_mm, installation_type, waste_outlet, electrical_required, voltage, power_w, material, color, features]
Index: []

In [13]:
print("Categories found:\n")

print(
    inspection_df["category"]
    .value_counts(dropna=False)
)

Categories found:

category
Faucet                  14
Toilet                   5
Bathroom sink            5
Other                    4
Sink                     2
Vessel                   1
BASINS / COUNTERTOP      1
Toilet Seat              1
Bathroom Sink            1
Faucet Trim              1
Bathroom sink faucet     1
Name: count, dtype: int64

In [14]:
print("Subcategories found:\n")

print(
    inspection_df["subcategory"]
    .value_counts(dropna=False)
)

Subcategories found:

subcategory
Not specified                              10
Vessel sink                                 5
Vessel                                      4
Bathroom sink faucet                        3
Health faucet                               3
Single-handle bathroom sink faucet          2
Countertop Basin                            1
One-piece elongated toilet                  1
One-piece toilet                            1
Wall-mount bathroom sink faucet             1
Tall single-handle bathroom sink faucet     1
One-piece round-front smart toilet          1
One-piece round-front toilet                1
Wall-mount bathroom sink faucet trim        1
Single-handle                               1
Name: count, dtype: int64

In [15]:
dimension_columns = [
    "width_mm",
    "depth_mm",
    "height_mm"
]

dimension_missing = inspection_df[
    inspection_df[dimension_columns]
    .isna()
    .any(axis=1)
]

print(
    "Products with at least one missing dimension:",
    len(dimension_missing)
)

display(
    dimension_missing[
        [
            "product_id",
            "product_name",
            "category",
            "width_mm",
            "depth_mm",
            "height_mm"
        ]
    ]
)

Products with at least one missing dimension: 0

Empty DataFrame
Columns: [product_id, product_name, category, width_mm, depth_mm, height_mm]
Index: []

In [16]:
invalid_dimensions = inspection_df[
    (
        inspection_df["width_mm"].notna()
        & (inspection_df["width_mm"] <= 0)
    )
    |
    (
        inspection_df["depth_mm"].notna()
        & (inspection_df["depth_mm"] <= 0)
    )
    |
    (
        inspection_df["height_mm"].notna()
        & (inspection_df["height_mm"] <= 0)
    )
]

print(
    "Products with invalid/non-positive dimensions:",
    len(invalid_dimensions)
)

display(invalid_dimensions)

Products with invalid/non-positive dimensions: 34

,product_id,product_name,category,subcategory,collection,width_mm,depth_mm,height_mm,rough_in_mm,installation_type,waste_outlet,electrical_required,voltage,power_w,material,color,features
2,1311520-A04-D,Mica® Square 393mm Basin,BASINS / COUNTERTOP,Countertop Basin,Not specified,393.0,393.0,-1.0,50.0,Bench top installation,DN32 waste without overflow,False,Not specified,-1.0,Ceramic,"[white, honed black]","[Bench top installation, Slim vessel, CleanCoa..."
3,K-12927IN,Complimentary™ Hygiene Spray,Other,Not specified,Not specified,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Not specified,"[Polished Chrome, Vibrant® French Gold, Vibran...",[Designed to coordinate with a range of KOHLER...
4,K-1381T-S,Veil™ One-piece elongated toilet with skirted ...,Toilet,One-piece elongated toilet,Veil,-1.0,-1.0,390.0,305.0,Floor-mount,Floor,False,Not specified,-1.0,Plastic seat,[White],[One-piece toilets integrate the tank and bowl...
5,K-17629T-NS,Ove™ One-piece round-front toilet with skirted...,Toilet,One-piece toilet,Ove™,-1.0,-1.0,390.0,185.0,Floor-mount,Floor,False,Not specified,-1.0,Not specified,[White],[One-piece toilets integrate the tank and bowl...
6,K-17660T-M,Ove™ Quiet-Close™ elongated toilet seat,Toilet Seat,Not specified,Not specified,-1.0,-1.0,-1.0,-1.0,Not specified,Not specified,False,Not specified,-1.0,Plastic construction,[White],"[Elongated closed-front seat with lid, Quiet-C..."
7,K-1851IN,Brive Plus,Other,Not specified,Not specified,-1.0,-1.0,395.0,180.0,Floor-mount,Floor,False,Not specified,-1.0,Not specified,[White],[Round-front bowl offers an ideal solution for...
8,K-1853IN,Brive Plus,Other,Not specified,Not specified,-1.0,-1.0,395.0,220.0,Floor-mount,Floor,False,Not specified,-1.0,Not specified,[White],"[Elongated bowl offers added room and comfort,..."
9,K-21226IN,ModernLife Edge 600 mm rectangular vessel bath...,Sink,Vessel sink,ModernLife Edge,600.0,113.0,-1.0,-1.0,Vessel,Not specified,False,Not specified,-1.0,Vitreous china,"[Honed Black, Thunder grey, Honed Peacock, Hon...","[Contemporary design makes a modern statement,..."
10,K-2200IN,Conical Bell™,Sink,Vessel sink,Not specified,413.0,-1.0,-1.0,464.0,Semi-recessed vessel,"Center drain, no overflow",False,Not specified,-1.0,Vitreous china,"[White, Cashmere, Black]","[Traditional design creates a classic look, Ro..."
11,K-23486IN-4ND,"Parallel™ Wall-mount bathroom sink faucet, 9.0...",Faucet,Wall-mount bathroom sink faucet,Parallel,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium metal,"[Polished Chrome, Vibrant French Gold, Vibrant...",[Single handle controls both on/off activation...
12,K-23966IN-4ND,KOHLER VIVE® Single-handle bathroom sink fauce...,Faucet,Single-handle bathroom sink faucet,Not specified,-1.0,-1.0,-1.0,-1.0,Single hole,Not specified,False,Not specified,-1.0,Premium metal construction,"[Polished Chrome, Vibrant® French Gold, Matte ...",[Single handle controls both on/off activation...
13,K-23967IN-4ND,KOHLER VIVE® Tall single-handle bathroom sink ...,Faucet,Tall single-handle bathroom sink faucet,VIVE,-1.0,-1.0,-1.0,-1.0,Single hole,Drain sold separately,False,Not specified,-1.0,Premium metal construction,"[Polished Chrome, Vibrant® French Gold, Matte ...",[Single handle controls both on/off activation...
14,K-25316IN,Span™ 537 mm rectangular vessel bathroom sink ...,Bathroom sink,Vessel sink,Not specified,537.0,-1.0,-1.0,-1.0,Vessel,Not specified,False,Not specified,-1.0,Vitreous china,[White],"[Minimalist design with thin, rounded edges, R..."
15,K-2661IN,Vox™ 413 mm square vessel bathroom sink,Bathroom sink,Vessel,Vox™,413.0,413.0,-1.0,-1.0,Semi-recessed vessel,Not specified,False,Not specified,-1.0,Vitreous china,"[White, Black]",[Deep square basin with a contemporary design ...
16,K-27477IN-4ND,"Fore Tri® Single-handle bathroom sink faucet, ...",Faucet,Single-handle bathroom sink faucet,Not specified,-1.0,-1.0,-1.0,-1.0,Deck-mount,Not specified,False,Not specified,-1.0,Premium material,[Polished Chrome],"[Sleek and contemporary design, Single handle ..."
17,K-27480IN-4ND,Fore Line™ Tall single-handle bathroom sink fa...,Faucet,Bathroom sink faucet,Fore Line™,-1.0,-1.0,-1.0,-1.0,Deck-mount,Not specified,False,Not specified,-1.0,Premium material,"[Polished Chrome, Vibrant® French Gold]","[Single handle provides on/off activation, vol..."
18,K-27485IN-4,"Fore Line™ Single-handle bathroom sink faucet,...",Faucet,Not specified,Fore Line™,-1.0,96.0,86.0,-1.0,"Deck-mount, single-hole installation",Not specified,False,Not specified,-1.0,Premium metal construction,"[Polished Chrome, Vibrant® French Gold]","[For use with cold water line only, Single han..."
19,K-28529IN,"Leap™ One-piece round-front smart toilet, dual...",Toilet,One-piece round-front smart toilet,Not specified,-1.0,-1.0,400.0,305.0,Floor-mount,Floor,True,220-240 V,1200.0,Plastic seat,[White],[One-piece toilets integrate the tank and bowl...
20,K-28784IN,KOHLER VIVE® 552 mm rectangular vessel bathroo...,Bathroom Sink,Vessel,Not specified,-1.0,-1.0,-1.0,-1.0,Semi-recessed vessel,Not specified,False,Not specified,-1.0,Vitreous china,"[White, Cashmere, Black, Indigo Gloss, Teak Be...","[Rectangular basin with rounded corners, Sleek..."
21,K-33123IN-HC,KOHLER VIVE Hidden cord one-piece round-front ...,Toilet,Not specified,Vive,-1.0,-1.0,400.0,220.0,Floor-mount,Floor,False,Not specified,-1.0,Not specified,[White],[One-piece toilets integrate the tank and bowl...
22,K-3983IN-S,Reach™ One-piece round-front toilet with skirt...,Toilet,One-piece round-front toilet,Reach™,-1.0,-1.0,391.0,305.0,Floor-mount,Floor,False,Not specified,-1.0,Plastic seat,[White],[One-piece toilets integrate the tank and bowl...
23,K-5373IN,Forefront™ 580 mm rectangular vessel bathroom ...,Bathroom sink,Vessel,Forefront™,-1.0,-1.0,-1.0,-1.0,Semi-recessed vessel,Not specified,False,Not specified,-1.0,Vitreous china,"[White, Cashmere, Black]",[Deep rectangular basin with a contemporary de...
24,K-5684IN-4ND,"Aleo+™ Wall-mount bathroom sink faucet trim, 9...",Faucet Trim,Wall-mount bathroom sink faucet trim,Aleo+,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium material construction,"[Polished Chrome, Vibrant® French Gold, Vibran...","[Sleek contemporary design, Single Lever handl..."
25,K-72298IN-4ND,"Aleo® Tall single-handle bathroom sink faucet,...",Faucet,Bathroom sink faucet,Aleo™,-1.0,-1.0,-1.0,-1.0,single-hole,Not specified,False,Not specified,-1.0,Premium metal,"[Polished Chrome, Vibrant® Brushed Bronze, Vib...","[Tall height is ideal for vessel-style sinks, ..."
26,K-72337IN-4ND,Aleo+™ Tall single-handle bathroom sink faucet...,Faucet,Bathroom sink faucet,Aleo+,-1.0,-1.0,-1.0,-1.0,Deck-mount,Not specified,False,Not specified,-1.0,Premium metal,"[Polished Chrome, Vibrant® French Gold, Vibran...","[Tall height is ideal for vessel-style sinks, ..."
27,K-75374IN-1,Forefront™ 460 mm square vessel bathroom sink ...,Bathroom sink,Vessel sink,Forefront™,460.0,460.0,-1.0,-1.0,Semi-recessed vessel,Not specified,False,Not specified,-1.0,Vitreous china,[White],"[Contemporary design makes a modern statement,..."
28,K-75375IN,Forefront™ 890 mm rectangular vessel bathroom ...,Bathroom sink,Vessel sink,Forefront™,-1.0,-1.0,120.0,-1.0,Vessel,Not specified,False,Not specified,-1.0,Vitreous china,[White],"[Contemporary design makes a modern statement,..."
29,K-75377IN-4,"July™ Single-handle bathroom sink faucet, cold...",Bathroom sink faucet,Not specified,July™,-1.0,-1.0,-1.0,-1.0,"Single-hole, Deck-mount",Not specified,False,Not specified,-1.0,Premium material,"[Polished Chrome, Vibrant® French Gold, Vibran...","[Versatile modern design, Single Lever handle ..."
30,K-77364IN,"Health faucet, 8.5 lpm",Faucet,Not specified,Luxe™,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Antimicrobial silicone,[Polished Chrome],"[Ergonomic, easy clean design, Optimized spray..."
31,K-97258IN-ZZ,"Elate™ Single-function health faucet, 8.5 lpm",Faucet,Health faucet,Not specified,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium material construction for durability a...,"[Vibrant® French Gold, Vibrant® Brushed Bronze...",[Single-function hygiene spray delivers a full...
32,K-97258IN,"Elate™ Single-function health faucet, 8.5 lpm",Faucet,Not specified,Not specified,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium material construction for durability a...,"[Polished Chrome, Matte Black]",[Single-function hygiene spray delivers a full...
33,K-97347T-4,Avid™ Tall Single-handle bathroom sink faucet,Faucet,Single-handle,Avid™ Tall,-1.0,-1.0,-1.0,-1.0,Not specified,Not specified,False,Not specified,-1.0,Brass,[Polished Chrome],[KOHLER ceramic disc valves exceed industry lo...
34,K-98100IN-ZZ,"Beam™ Health faucet, 10 lpm",Faucet,Health faucet,Not specified,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium material,[Matte Black],"[Contemporary styling matches any decor, Easy ..."
35,K-98100IN,"Cuff™ Single-function health faucet, 11.5 lpm",Faucet,Health faucet,Not specified,-1.0,-1.0,-1.0,-1.0,Wall-mount,Not specified,False,Not specified,-1.0,Premium material construction,"[Polished Chrome, White]","[Contemporary styling matches any decor, Easy ..."

In [17]:
installation_columns = [
    "rough_in_mm",
    "installation_type",
    "waste_outlet"
]

display(
    inspection_df[
        [
            "product_id",
            "product_name",
            "category"
        ] + installation_columns
    ]
)

,product_id,product_name,category,rough_in_mm,installation_type,waste_outlet
0,1408991-IN4-A,SPAN® Square Vessel Without Deck ( Small),Other,-1.0,Above Counter,Not specified
1,29024IN-1,CHALICE ROUND VESSEL 1TAP HOLE,Vessel,-1.0,Above counter,Not specified
2,1311520-A04-D,Mica® Square 393mm Basin,BASINS / COUNTERTOP,50.0,Bench top installation,DN32 waste without overflow
3,K-12927IN,Complimentary™ Hygiene Spray,Other,-1.0,Wall-mount,Not specified
4,K-1381T-S,Veil™ One-piece elongated toilet with skirted ...,Toilet,305.0,Floor-mount,Floor
5,K-17629T-NS,Ove™ One-piece round-front toilet with skirted...,Toilet,185.0,Floor-mount,Floor
6,K-17660T-M,Ove™ Quiet-Close™ elongated toilet seat,Toilet Seat,-1.0,Not specified,Not specified
7,K-1851IN,Brive Plus,Other,180.0,Floor-mount,Floor
8,K-1853IN,Brive Plus,Other,220.0,Floor-mount,Floor
9,K-21226IN,ModernLife Edge 600 mm rectangular vessel bath...,Sink,-1.0,Vessel,Not specified
10,K-2200IN,Conical Bell™,Sink,464.0,Semi-recessed vessel,"Center drain, no overflow"
11,K-23486IN-4ND,"Parallel™ Wall-mount bathroom sink faucet, 9.0...",Faucet,-1.0,Wall-mount,Not specified
12,K-23966IN-4ND,KOHLER VIVE® Single-handle bathroom sink fauce...,Faucet,-1.0,Single hole,Not specified
13,K-23967IN-4ND,KOHLER VIVE® Tall single-handle bathroom sink ...,Faucet,-1.0,Single hole,Drain sold separately
14,K-25316IN,Span™ 537 mm rectangular vessel bathroom sink ...,Bathroom sink,-1.0,Vessel,Not specified
15,K-2661IN,Vox™ 413 mm square vessel bathroom sink,Bathroom sink,-1.0,Semi-recessed vessel,Not specified
16,K-27477IN-4ND,"Fore Tri® Single-handle bathroom sink faucet, ...",Faucet,-1.0,Deck-mount,Not specified
17,K-27480IN-4ND,Fore Line™ Tall single-handle bathroom sink fa...,Faucet,-1.0,Deck-mount,Not specified
18,K-27485IN-4,"Fore Line™ Single-handle bathroom sink faucet,...",Faucet,-1.0,"Deck-mount, single-hole installation",Not specified
19,K-28529IN,"Leap™ One-piece round-front smart toilet, dual...",Toilet,305.0,Floor-mount,Floor
20,K-28784IN,KOHLER VIVE® 552 mm rectangular vessel bathroo...,Bathroom Sink,-1.0,Semi-recessed vessel,Not specified
21,K-33123IN-HC,KOHLER VIVE Hidden cord one-piece round-front ...,Toilet,220.0,Floor-mount,Floor
22,K-3983IN-S,Reach™ One-piece round-front toilet with skirt...,Toilet,305.0,Floor-mount,Floor
23,K-5373IN,Forefront™ 580 mm rectangular vessel bathroom ...,Bathroom sink,-1.0,Semi-recessed vessel,Not specified
24,K-5684IN-4ND,"Aleo+™ Wall-mount bathroom sink faucet trim, 9...",Faucet Trim,-1.0,Wall-mount,Not specified
25,K-72298IN-4ND,"Aleo® Tall single-handle bathroom sink faucet,...",Faucet,-1.0,single-hole,Not specified
26,K-72337IN-4ND,Aleo+™ Tall single-handle bathroom sink faucet...,Faucet,-1.0,Deck-mount,Not specified
27,K-75374IN-1,Forefront™ 460 mm square vessel bathroom sink ...,Bathroom sink,-1.0,Semi-recessed vessel,Not specified
28,K-75375IN,Forefront™ 890 mm rectangular vessel bathroom ...,Bathroom sink,-1.0,Vessel,Not specified
29,K-75377IN-4,"July™ Single-handle bathroom sink faucet, cold...",Bathroom sink faucet,-1.0,"Single-hole, Deck-mount",Not specified
30,K-77364IN,"Health faucet, 8.5 lpm",Faucet,-1.0,Wall-mount,Not specified
31,K-97258IN-ZZ,"Elate™ Single-function health faucet, 8.5 lpm",Faucet,-1.0,Wall-mount,Not specified
32,K-97258IN,"Elate™ Single-function health faucet, 8.5 lpm",Faucet,-1.0,Wall-mount,Not specified
33,K-97347T-4,Avid™ Tall Single-handle bathroom sink faucet,Faucet,-1.0,Not specified,Not specified
34,K-98100IN-ZZ,"Beam™ Health faucet, 10 lpm",Faucet,-1.0,Wall-mount,Not specified
35,K-98100IN,"Cuff™ Single-function health faucet, 11.5 lpm",Faucet,-1.0,Wall-mount,Not specified

In [18]:
for product in products:

    print("=" * 80)

    print("Product ID:", product.get("product_id"))
    print("Product:", product.get("product_name"))
    print("Category:", product.get("category"))

    print("\nFeatures:")

    features = product.get("features", [])

    if features:
        for feature in features:
            print(" -", feature)
    else:
        print(" - No features extracted")

================================================================================
Product ID: 1408991-IN4-A
Product: SPAN® Square Vessel Without Deck ( Small)
Category: Other

Features:
 - Ergonomic and Straight line design suitable for compact rooms with deck space.
 - Easy installation as it requires counter cutting to accommodate drain only.
 - Optimum Depth to contain Splashes.
 - Above counter without faucet deck.
 - Only drain cutting (no profile cutting required).
 - Without Overflow Hole
================================================================================
Product ID: 29024IN-1
Product: CHALICE ROUND VESSEL 1TAP HOLE
Category: Vessel

Features:
 - Vitreous China
 - Circular Design
 - Without Overflow
 - Above counter
 - Only Drain cutting (no profile cutting required)
================================================================================
Product ID: 1311520-A04-D
Product: Mica® Square 393mm Basin
Category: BASINS / COUNTERTOP

Features:
 - Bench top installation
 - Slim vessel
 - CleanCoatTM - stain resistant & easy to clean
================================================================================
Product ID: K-12927IN
Product: Complimentary™ Hygiene Spray
Category: Other

Features:
 - Designed to coordinate with a range of KOHLER faucets
 - Thread = G 1/2
 - Includes wall-mount bracket
 - Includes hose
 - Handshower rated max flow: 3.3 gal/min (12.5 l/min)
================================================================================
Product ID: K-1381T-S
Product: Veil™ One-piece elongated toilet with skirted trapway, dual-flush
Category: Toilet

Features:
 - One-piece toilets integrate the tank and bowl into a seamless, easy-to-clean design
 - Elongated bowl offers added room and comfort
 - Dual-flush offers a choice of 0.8 or 1.28 gpf (3.0 or 4.5 lpf)
 - Washdown flushing system
 - Left-hand Polished Chrome trip lever
 - 52 mm (2 inch) fully glazed trapway
 - Fully skirted trapway simplifies cleaning
 - Seat and lid included
 - Quiet-Close™ functionality to prevent seat from slamming
 - Quick-Attach™ hardware for fast and secure installation
 - Quick-Release™ functionality allows seat to be removed easily from toilet for convenient cleaning
 - Coordinates with other products in the Veil collection
 - Compatible with C3™ and PureWash™ electronic bidet seats (sold separately)
================================================================================
Product ID: K-17629T-NS
Product: Ove™ One-piece round-front toilet with skirted trapway, dual-flush
Category: Toilet

Features:
 - One-piece toilets integrate the tank and bowl into a seamless, easy-to-clean design
 - Round-front bowl offers an ideal solution for smaller bathrooms and powder rooms
 - Rim-to-floor height: 390 mm (15-3/8 inches)
 - Top-mount Polished Chrome dual-flush button offers a choice of 0.8 or 1.6 gpf (3.0 or 6.0 lpf)
 - 58 mm (2-5/16 inch) fully glazed trapway
 - Fully skirted trapway simplifies cleaning
 - Coordinates with other products in the Ove™ collection
 - Compatible with C3™ toilet seats and the Ove™ Quiet-Close toilet seat and lid (sold separately)
================================================================================
Product ID: K-17660T-M
Product: Ove™ Quiet-Close™ elongated toilet seat
Category: Toilet Seat

Features:
 - Elongated closed-front seat with lid
 - Quiet-Close™ functionality to prevent seat from slamming
 - ReadyLatch™ hinge provides a positive lock/unlock latch to securely hold seat in position, yet seat easily removes for cleaning or adjusting fit
 - Quick-Release™ functionality allows seat to be removed easily from toilet for convenient cleaning
 - Quick-Attach™ hardware for fast and secure installation
 - Grip-Tight bumpers hold seat firmly in place
================================================================================
Product ID: K-1851IN
Product: Brive Plus
Category: Other

Features:
 - Round-front bowl offers an ideal solution for smaller bathrooms and powder rooms
 - Rim-to-floor height: 15.55 inches (395 mm)
 - Washdown flushing system
 - 65 mm (2-1/2 inch) fully glazed trapway
 - Concealed trapway brings an enhanced design to the bathroom and facilitates easy cleaning
 - Antimicrobial finish inhibits the growth of mold-, mildew-, stain-, and odor-causing bacteria on the fixture surface
 - Bowl only; requires tank and toilet seat (sold separately)
================================================================================
Product ID: K-1853IN
Product: Brive Plus
Category: Other

Features:
 - Elongated bowl offers added room and comfort
 - Rim-to-floor height: 15.55 inches (395 mm)
 - Washdown flushing system
 - 2 inch (51 mm) fully glazed trapway
 - Concealed trapway brings an enhanced design to the bathroom and facilitates easy cleaning
 - Bowl only; requires tank and toilet seat (sold separately)
================================================================================
Product ID: K-21226IN
Product: ModernLife Edge 600 mm rectangular vessel bathroom sink, no overflow
Category: Sink

Features:
 - Contemporary design makes a modern statement
 - Rectangular basin with rounded corners
 - No faucet holes; requires wall- or deck-mount faucet
 - Without overflow
 - Part of the ModernLife Edge collection
 - Faucet and drain sold separately
================================================================================
Product ID: K-2200IN
Product: Conical Bell™
Category: Sink

Features:
 - Traditional design creates a classic look
 - Round basin
 - No faucet holes; requires wall- or tall deck-mount faucet
 - Center drain, no overflow
 - Glazed underside offers beauty from all angles
================================================================================
Product ID: K-23486IN-4ND
Product: Parallel™ Wall-mount bathroom sink faucet, 9.0 lpm
Category: Faucet

Features:
 - Single handle controls both on/off activation and temperature setting
 - 164 mm spout reach
 - 9.0 lpm maximum flow rate at 3.0 bar
 - KOHLER ceramic disc valves exceed industry longevity standards for a lifetime of durable performance
 - Coordinates with other products in the Parallel collection
================================================================================
Product ID: K-23966IN-4ND
Product: KOHLER VIVE® Single-handle bathroom sink faucet, 7.0 lpm
Category: Faucet

Features:
 - Single handle controls both on/off activation and temperature setting
 - Spout height 2-13/32" (61 mm)
 - Spout reach 4-5/8" (117 mm)
 - Maximum flow rate 1.8 gpm (7.0 lpm) at 43.5 psi (3.0 bar)
 - Premium metal construction for durability and reliability
 - KOHLER finishes resist corrosion and tarnishing
================================================================================
Product ID: K-23967IN-4ND
Product: KOHLER VIVE® Tall single-handle bathroom sink faucet, 5.5 lpm
Category: Faucet

Features:
 - Single handle controls both on/off activation and temperature setting
 - 7.19 inch (183 mm) spout height
 - 5.16 inch (131 mm) spout reach
 - 1.5 gpm (5.5 lpm) maximum flow rate at 43.5 psi (3.0 bar)
 - KOHLER finishes resist corrosion and tarnishing
================================================================================
Product ID: K-25316IN
Product: Span™ 537 mm rectangular vessel bathroom sink with glazed underside, no overflow
Category: Bathroom sink

Features:
 - Minimalist design with thin, rounded edges
 - Rectangular basin
 - Integrated faucet deck provides additional water containment
 - Single faucet hole at deck center
 - Without overflow
 - Glazed underside offers beauty from all angles
================================================================================
Product ID: K-2661IN
Product: Vox™ 413 mm square vessel bathroom sink
Category: Bathroom sink

Features:
 - Deep square basin with a contemporary design minimizes splash
 - No faucet holes; requires wall- or deck-mount faucet
 - Center drain
 - With overflow and overflow cover
================================================================================
Product ID: K-27477IN-4ND
Product: Fore Tri® Single-handle bathroom sink faucet, 19.2 lpm
Category: Faucet

Features:
 - Sleek and contemporary design
 - Single handle provides on/off activation, volume, and temperature control
 - Red/blue indexing on handle
 - 3.94 inch (100 mm) spout reach
 - 5.81 inch (148 mm) spout height
 - Aerated flow
 - 5.08 gpm (19.2 lpm) maximum flow rate at 80 psi (5.5 bar)
 - KOHLER® ceramic disc valves exceed industry longevity standards for a lifetime of durable performance
 - Drain sold separately
================================================================================
Product ID: K-27480IN-4ND
Product: Fore Line™ Tall single-handle bathroom sink faucet, 11.0 lpm
Category: Faucet

Features:
 - Single handle provides on/off activation, volume, and temperature control
 - Red/blue indexing on handle
 - 124 mm (4.87 inch) spout reach
 - 200 mm (7.88 inch) spout height
 - Tall height is ideal for vessel-style sinks
 - 2.9 gpm (11.0 lpm) maximum flow rate at 80 psi (5.5 bar)
 - Aerated flow
 - KOHLER® ceramic disc valves exceed industry longevity standards for a lifetime of durable performance
 - Drain sold separately
================================================================================
Product ID: K-27485IN-4
Product: Fore Line™ Single-handle bathroom sink faucet, cold only, 18.4 lpm
Category: Faucet

Features:
 - For use with cold water line only
 - Single handle provides on/off activation and volume control
 - 86 mm (3.4 inch) spout height
 - 96 mm (3.76 inch) spout reach
 - 4.22 gpm (16.0 lpm) maximum flow rate at 43.5 psi (3.0 bar)
 - KOHLER ceramic disc valves exceed industry longevity standards by over two times, ensuring durable performance for life
 - Drain sold separately
 - Includes installation hardware
 - Premium metal construction for durability and reliability
 - KOHLER finishes resist corrosion and tarnishing
================================================================================
Product ID: K-28529IN
Product: Leap™ One-piece round-front smart toilet, dual-flush
Category: Toilet

Features:
 - One-piece toilets integrate the tank and bowl into a seamless, easy-to-clean design
 - Round-front bowl offers an ideal solution for smaller bathrooms and powder rooms
 - Dual-flush offers a choice of 0.8 or 1.2 gpf (3.0 or 4.5 lpf)
 - Touchless technology allows hands-free operation to actuate the flush
 - Automatic flushing after every use; flush can also be controlled by the remote control or backup button
 - Manual flush button on control panel
 - Fully skirted trapway simplifies cleaning
 - 1.9 inch (49 mm) fully glazed trapway
 - Includes bidet seat
 - Quiet-Close™ functionality to prevent seat from slamming
 - Grip-Tight bumpers hold seat firmly in place
 - Stainless steel wand offers adjustable spray shape, position, water pressure, temperature, pulsate, and oscillate functions
 - Front and rear wash modes provide warm water for cleansing
 - Self-cleaning function uses UV light to automatically sanitize the wand surfaces
 - Motion-activated, hands-free opening/closing of cover
 - Warm-air drying system
 - Heated seat with adjustable temperature settings
 - Seat features automatic deodorization
 - Energy Save feature monitors usage and adjusts heated seat settings to save energy
================================================================================
Product ID: K-28784IN
Product: KOHLER VIVE® 552 mm rectangular vessel bathroom sink, no overflow
Category: Bathroom Sink

Features:
 - Rectangular basin with rounded corners
 - Sleek and contemporary design
 - Unique front slotted drain creates a sleek look
 - Hidden drain connector maintains design continuity
 - Without overflow
 - No faucet holes; requires wall- or tall counter-mount faucet
================================================================================
Product ID: K-33123IN-HC
Product: KOHLER VIVE Hidden cord one-piece round-front back-to-wall toilet with skirted trapway, dual-flush
Category: Toilet

Features:
 - One-piece toilets integrate the tank and bowl into a seamless, easy-to-clean design
 - Round-front bowl
 - Back-to-wall design prevents dirt buildup for improved hygiene
 - Rimless design makes toilet bowl more hygienic and easier to clean
 - Top-mount polished chrome dual-flush button offers a choice of 3.0 or 4.5 lpf (0.8 or 1.28 gpf)
 - 60 mm fully glazed trapway
 - Fully skirted trapway simplifies cleaning and looks elegant
 - Washdown flushing system
 - Coordinates with other products in the Vive collection
 - Hidden cord design conceals bidet seat cords (bidet seat sold separately)
 - Compatible with PureWash manual bidet seat
================================================================================
Product ID: K-3983IN-S
Product: Reach™ One-piece round-front toilet with skirted trapway, dual-flush
Category: Toilet

Features:
 - One-piece toilets integrate the tank and bowl into a seamless, easy-to-clean design
 - Round-front bowl offers an ideal solution for smaller bathrooms and powder rooms
 - Top-mount polished chrome dual-flush button offers a choice of 1.0 or 1.28 gpf (3.3 or 4.8 lpf)
 - Class Five™ flushing technology provides powerful flushing performance and best-in-class bowl cleanliness
 - 2.44 inch (62 mm) fully glazed trapway
 - Fully skirted trapway simplifies cleaning
 - Round-front seat with lid
 - Quiet-Close™ functionality to prevent seat from slamming
 - Coordinates with other products in the Reach™ collection
================================================================================
Product ID: K-5373IN
Product: Forefront™ 580 mm rectangular vessel bathroom sink
Category: Bathroom sink

Features:
 - Deep rectangular basin with a contemporary design minimizes splash
 - No faucet holes; requires wall- or deck-mount faucet
 - Center drain
 - With overflow and overflow cover
================================================================================
Product ID: K-5684IN-4ND
Product: Aleo+™ Wall-mount bathroom sink faucet trim, 9.0 lpm
Category: Faucet Trim

Features:
 - Sleek contemporary design
 - Single Lever handle allows for on/off activation, volume, and temperature control
 - 160 mm (6.3 inch) spout reach
 - Aerated flow
 - 9.0 lpm (2.38 gpm) maximum flow rate at 3.0 bar (43.5 psi)
 - Drain sold separately
 - Premium material construction for durability and reliability
 - KOHLER finishes resist corrosion and tarnishing
================================================================================
Product ID: K-72298IN-4ND
Product: Aleo® Tall single-handle bathroom sink faucet, 8.9 lpm
Category: Faucet

Features:
 - Tall height is ideal for vessel-style sinks
 - Single Lever handle allows for on/off activation, volume, and temperature control
 - Aerated flow
 - 160 mm (6.3 inch) spout reach
 - 212 mm (8.33 inch) spout height
 - 8.33 inch (212 mm) spout height
 - 2.37 gpm (8.9 lpm) maximum flow rate at 60 psi (4.14 bar)
 - KOHLER® ceramic disc valves exceed industry longevity standards for a lifetime of durable performance
 - Coordinates with other products in the Aleo™ collection
 - Drain sold separately
================================================================================
Product ID: K-72337IN-4ND
Product: Aleo+™ Tall single-handle bathroom sink faucet, 14.0 lpm
Category: Faucet

Features:
 - Tall height is ideal for vessel-style sinks
 - Single Lever handle allows for on/off activation, volume, and temperature control
 - 6.22 inch (158 mm) spout reach
 - 8.31 inch (211 mm) spout height
 - 14.0 lpm (3.69 gpm) maximum flow rate at 3.0 bar (43.5 psi)
 - Aerated flow
 - KOHLER ceramic disc valves exceed industry longevity standards by over two times, ensuring durable performance for life
================================================================================
Product ID: K-75374IN-1
Product: Forefront™ 460 mm square vessel bathroom sink with glazed underside, no overflow
Category: Bathroom sink

Features:
 - Contemporary design makes a modern statement
 - Square basin
 - Rounded corners are easy to clean
 - An integrated faucet deck provides additional water containment
 - Single faucet hole at deck center
 - Without overflow
 - Glazed underside offers beauty from all angles
 - Coordinates with other products in the Forefront™ collection
================================================================================
Product ID: K-75375IN
Product: Forefront™ 890 mm rectangular vessel bathroom sink, no overflow
Category: Bathroom sink

Features:
 - Contemporary design makes a modern statement
 - Elongated, rectangular basin
 - Shallow basin creates a sleek look
 - No faucet holes; requires wall- or deck-mount faucet
 - Without overflow
 - Coordinates with other products in the Forefront™ collection
================================================================================
Product ID: K-75377IN-4
Product: July™ Single-handle bathroom sink faucet, cold only, 27.0 lpm
Category: Bathroom sink faucet

Features:
 - Versatile modern design
 - Single Lever handle provides on/off activation and volume control
 - For use with cold water line only
 - 90 mm (3.5 inch) spout reach
 - 75 mm (2.95 inch) spout height
 - Aerated flow
 - 27.0 lpm (7.13 gpm) maximum flow rate at 3.0 bar (43.5 psi)
 - KOHLER® ceramic disc valves exceed industry longevity standards for a lifetime of durable performance
 - Premium material construction for durability and reliability
 - KOHLER finishes resist corrosion and tarnishing
================================================================================
Product ID: K-77364IN
Product: Health faucet, 8.5 lpm
Category: Faucet

Features:
 - Ergonomic, easy clean design
 - Optimized sprayface for maximum performance
 - Precision flow control meets all user needs regardless of your home's water pressure
 - 8.5 lpm (2.25 gpm) maximum flow rate at 3.0 bar (43.5 psi)
 - Includes 1200 mm (47.24 inch) hose and wall-mount holder
================================================================================
Product ID: K-97258IN-ZZ
Product: Elate™ Single-function health faucet, 8.5 lpm
Category: Faucet

Features:
 - Single-function hygiene spray delivers a full, consistent stream, regardless of water pressure
 - Soft spray pattern
 - Ergonomic button design
 - 2.25 gpm (8.5 lpm) maximum flow rate at 43.5 psi (3.0 bar)
 - Includes 59.06 inch (1500 mm) smooth hose and wall-mount holder
 - Includes a screen washer to prevent clogging
================================================================================
Product ID: K-97258IN
Product: Elate™ Single-function health faucet, 8.5 lpm
Category: Faucet

Features:
 - Single-function hygiene spray delivers a full, consistent stream, regardless of water pressure
 - Soft spray pattern
 - Ergonomic button design
 - 2.25 gpm (8.5 lpm) maximum flow rate at 43.5 psi (3.0 bar)
 - Includes 1200 mm (47.24 inch) hose and wall-mount holder
 - Includes a screen washer to prevent clogging
================================================================================
Product ID: K-97347T-4
Product: Avid™ Tall Single-handle bathroom sink faucet
Category: Faucet

Features:
 - KOHLER ceramic disc valves exceed industry longevity standards for a lifetime of durable performance
 - Lever handle
 - Spout reach 148 mm
 - Includes flexible G 1/2 supply hoses for easy installation
 - Includes drain
 - Directionally adjustable, laminar-flow aerator
================================================================================
Product ID: K-98100IN-ZZ
Product: Beam™ Health faucet, 10 lpm
Category: Faucet

Features:
 - Contemporary styling matches any decor
 - Easy grip design with special anti-slipping features
 - Single-function hygiene spray delivers a full, consistent stream, regardless of water pressure
 - 10.0 lpm (2.64 gpm) maximum flow rate at 3.0 bar (43.5 psi)
 - Includes 59-1/16" (1500 mm) hose and wall-mount holder

In [19]:
for product in products:

    color = product.get("color")

    print(
        product.get("product_id"),
        "→",
        color
    )

1408991-IN4-A → ['White']
29024IN-1 → ['White']
1311520-A04-D → ['white', 'honed black']
K-12927IN → ['Polished Chrome', 'Vibrant® French Gold', 'Vibrant® Brushed Nickel']
K-1381T-S → ['White']
K-17629T-NS → ['White']
K-17660T-M → ['White']
K-1851IN → ['White']
K-1853IN → ['White']
K-21226IN → ['Honed Black', 'Thunder grey', 'Honed Peacock', 'Honed Lush']
K-2200IN → ['White', 'Cashmere', 'Black']
K-23486IN-4ND → ['Polished Chrome', 'Vibrant French Gold', 'Vibrant Brushed Bronze', 'Matte Black', 'Vibrant Rose Gold', 'Vibrant Brushed Rose Gold']
K-23966IN-4ND → ['Polished Chrome', 'Vibrant® French Gold', 'Matte Black', 'Vibrant Rose Gold']
K-23967IN-4ND → ['Polished Chrome', 'Vibrant® French Gold', 'Matte Black', 'Vibrant Rose Gold']
K-25316IN → ['White']
K-2661IN → ['White', 'Black']
K-27477IN-4ND → ['Polished Chrome']
K-27480IN-4ND → ['Polished Chrome', 'Vibrant® French Gold']
K-27485IN-4 → ['Polished Chrome', 'Vibrant® French Gold']
K-28529IN → ['White']
K-28784IN → ['White', 'Cashmere', 'Black', 'Indigo Gloss', 'Teak Berry']
K-33123IN-HC → ['White']
K-3983IN-S → ['White']
K-5373IN → ['White', 'Cashmere', 'Black']
K-5684IN-4ND → ['Polished Chrome', 'Vibrant® French Gold', 'Vibrant® Brushed Nickel', 'Vibrant® Brushed Bronze', 'Matte Black', 'Vibrant Brushed Rose Gold']
K-72298IN-4ND → ['Polished Chrome', 'Vibrant® Brushed Bronze', 'Vibrant Rose Gold', 'Vibrant Brushed Rose Gold']
K-72337IN-4ND → ['Polished Chrome', 'Vibrant® French Gold', 'Vibrant® Brushed Nickel', 'Vibrant® Brushed Bronze', 'Matte Black', 'Vibrant Rose Gold', 'Vibrant Brushed Rose Gold']
K-75374IN-1 → ['White']
K-75375IN → ['White']
K-75377IN-4 → ['Polished Chrome', 'Vibrant® French Gold', 'Vibrant® Brushed Nickel']
K-77364IN → ['Polished Chrome']
K-97258IN-ZZ → ['Vibrant® French Gold', 'Vibrant® Brushed Bronze', 'Matte Black', 'Vibrant Rose Gold', 'Vibrant Brushed Rose Gold']
K-97258IN → ['Polished Chrome', 'Matte Black']
K-97347T-4 → ['Polished Chrome']
K-98100IN-ZZ → ['Matte Black']
K-98100IN → ['Polished Chrome', 'White']

In [20]:
validation_issues = []

for product in products:

    problems = product.get(
        "validation_problems",
        []
    )

    if problems:

        validation_issues.append({
            "product_id": product.get("product_id"),
            "product_name": product.get("product_name"),
            "problems": problems
        })

print(
    "Products with validation warnings:",
    len(validation_issues)
)

display(
    pd.DataFrame(validation_issues)
)

Products with validation warnings: 35

,product_id,product_name,problems
0,1408991-IN4-A,SPAN® Square Vessel Without Deck ( Small),[Missing category]
1,1311520-A04-D,Mica® Square 393mm Basin,[Missing height]
2,K-12927IN,Complimentary™ Hygiene Spray,"[Missing category, Missing width, Missing dept..."
3,K-1381T-S,Veil™ One-piece elongated toilet with skirted ...,"[Missing width, Missing depth]"
4,K-17629T-NS,Ove™ One-piece round-front toilet with skirted...,"[Missing width, Missing depth]"
5,K-17660T-M,Ove™ Quiet-Close™ elongated toilet seat,"[Missing width, Missing depth, Missing height]"
6,K-1851IN,Brive Plus,"[Missing category, Missing width, Missing depth]"
7,K-1853IN,Brive Plus,"[Missing category, Missing width, Missing depth]"
8,K-21226IN,ModernLife Edge 600 mm rectangular vessel bath...,[Missing height]
9,K-2200IN,Conical Bell™,"[Missing depth, Missing height]"
10,K-23486IN-4ND,"Parallel™ Wall-mount bathroom sink faucet, 9.0...","[Missing width, Missing depth, Missing height]"
11,K-23966IN-4ND,KOHLER VIVE® Single-handle bathroom sink fauce...,"[Missing width, Missing depth, Missing height]"
12,K-23967IN-4ND,KOHLER VIVE® Tall single-handle bathroom sink ...,"[Missing width, Missing depth, Missing height]"
13,K-25316IN,Span™ 537 mm rectangular vessel bathroom sink ...,"[Missing depth, Missing height]"
14,K-2661IN,Vox™ 413 mm square vessel bathroom sink,[Missing height]
15,K-27477IN-4ND,"Fore Tri® Single-handle bathroom sink faucet, ...","[Missing width, Missing depth, Missing height]"
16,K-27480IN-4ND,Fore Line™ Tall single-handle bathroom sink fa...,"[Missing width, Missing depth, Missing height]"
17,K-27485IN-4,"Fore Line™ Single-handle bathroom sink faucet,...",[Missing width]
18,K-28529IN,"Leap™ One-piece round-front smart toilet, dual...","[Missing width, Missing depth]"
19,K-28784IN,KOHLER VIVE® 552 mm rectangular vessel bathroo...,"[Missing width, Missing depth, Missing height]"
20,K-33123IN-HC,KOHLER VIVE Hidden cord one-piece round-front ...,"[Missing width, Missing depth]"
21,K-3983IN-S,Reach™ One-piece round-front toilet with skirt...,"[Missing width, Missing depth]"
22,K-5373IN,Forefront™ 580 mm rectangular vessel bathroom ...,"[Missing width, Missing depth, Missing height]"
23,K-5684IN-4ND,"Aleo+™ Wall-mount bathroom sink faucet trim, 9...","[Missing width, Missing depth, Missing height]"
24,K-72298IN-4ND,"Aleo® Tall single-handle bathroom sink faucet,...","[Missing width, Missing depth, Missing height]"
25,K-72337IN-4ND,Aleo+™ Tall single-handle bathroom sink faucet...,"[Missing width, Missing depth, Missing height]"
26,K-75374IN-1,Forefront™ 460 mm square vessel bathroom sink ...,[Missing height]
27,K-75375IN,Forefront™ 890 mm rectangular vessel bathroom ...,"[Missing width, Missing depth]"
28,K-75377IN-4,"July™ Single-handle bathroom sink faucet, cold...","[Missing width, Missing depth, Missing height]"
29,K-77364IN,"Health faucet, 8.5 lpm","[Missing width, Missing depth, Missing height]"
30,K-97258IN-ZZ,"Elate™ Single-function health faucet, 8.5 lpm","[Missing width, Missing depth, Missing height]"
31,K-97258IN,"Elate™ Single-function health faucet, 8.5 lpm","[Missing width, Missing depth, Missing height]"
32,K-97347T-4,Avid™ Tall Single-handle bathroom sink faucet,"[Missing width, Missing depth, Missing height]"
33,K-98100IN-ZZ,"Beam™ Health faucet, 10 lpm","[Missing width, Missing depth, Missing height]"
34,K-98100IN,"Cuff™ Single-function health faucet, 11.5 lpm","[Missing width, Missing depth, Missing height]"

In [21]:
print(
    inspection_df.shape
)

print("\nExtraction status:")

status_counts = pd.DataFrame(products)[
    "extraction_status"
].value_counts(dropna=False)

display(status_counts)

(36, 17)

Extraction status:

extraction_status
success    36
Name: count, dtype: int64

In [22]:
important_fields = [
    "product_id",
    "product_name",
    "category"
]

suspicious_products = []

for product in products:

    missing_important = []

    for field in important_fields:

        value = product.get(field)

        if value is None or str(value).strip() == "":
            missing_important.append(field)

    if missing_important:

        suspicious_products.append({
            "product_id": product.get("product_id"),
            "product_name": product.get("product_name"),
            "missing_important_fields": missing_important,
            "source_pdf": product.get("source_pdf")
        })

print(
    "Suspicious products:",
    len(suspicious_products)
)

display(
    pd.DataFrame(suspicious_products)
)

Suspicious products: 0

Empty DataFrame
Columns: []
Index: []

In [23]:
inspection_path = Path(
    "kohler_data_cleaning_inspection.csv"
)

inspection_df.to_csv(
    inspection_path,
    index=False
)

print(
    "Inspection report saved to:"
)

print(
    inspection_path.resolve()
)

Inspection report saved to:
C:\Users\Abhist\Desktop\KOHLER\scripts\kohler_data_cleaning_inspection.csv

In [24]:
# Backup the current extracted products

backup_collection = db["products_backup"]

# Remove an old backup if you previously created one
backup_collection.delete_many({})

# Copy all current products
current_products = list(
    products_collection.find({})
)

if current_products:
    backup_collection.insert_many(current_products)

print(
    f"Backup created successfully: {len(current_products)} products"
)

Backup created successfully: 36 products

# Final Missing-Value Cleaning

This section converts missing values into explicit, safe placeholders rather than inventing product specifications.

**Important:** `-1` means the numeric specification was not available in the source data. It is NOT a real product dimension. The corresponding `*_available` flag tells the recommendation/layout engine whether that value may be used for calculations.

Text fields use `Not specified`, list fields use `['Not specified']`, and missing categories use `Other`. Original values are preserved in `category_original` and `subcategory_original` where useful.

In [25]:
# ============================================
# 1. RELOAD PRODUCTS BEFORE CLEANING
# ============================================

products = list(products_collection.find({}, {"_id": 0}))

print(f"Products loaded for cleaning: {len(products)}")
assert len(products) > 0, "No products found in MongoDB."

Products loaded for cleaning: 36

In [26]:
# ============================================
# 2. CLEANING RULES
# ============================================

# Numeric fields use -1 when the source does not provide a value.
# NEVER interpret -1 as a real dimension/specification.
NUMERIC_FIELDS = [
    "width_mm",
    "depth_mm",
    "height_mm",
    "rough_in_mm",
    "power_w"
]

TEXT_FIELDS = [
    "product_id",
    "product_name",
    "category",
    "subcategory",
    "collection",
    "installation_type",
    "waste_outlet",
    "voltage",
    "material"
]

LIST_FIELDS = [
    "color",
    "features"
]

print("Cleaning rules loaded.")

Cleaning rules loaded.

In [27]:
# ============================================
# 3. HELPER FUNCTIONS
# ============================================

def is_blank(value):
    """Return True for None, NaN, empty strings, or empty containers."""
    if value is None:
        return True

    if isinstance(value, float) and pd.isna(value):
        return True

    if isinstance(value, str) and value.strip() == "":
        return True

    if isinstance(value, (list, dict)) and len(value) == 0:
        return True

    return False


def clean_text(value):
    """Clean text while preserving the fact that the source did not specify it."""
    if is_blank(value):
        return "Not specified"
    return str(value).strip()


def clean_numeric(value):
    """Convert numeric values to float; use -1 for unavailable source values."""
    if is_blank(value):
        return -1.0

    try:
        number = float(value)
        return number if number > 0 else -1.0
    except (TypeError, ValueError):
        return -1.0


def clean_list(value):
    """Ensure list fields never contain null/empty values."""
    if is_blank(value):
        return ["Not specified"]

    if not isinstance(value, list):
        value = [value]

    cleaned = []
    for item in value:
        if not is_blank(item):
            cleaned.append(str(item).strip())

    return cleaned if cleaned else ["Not specified"]

In [28]:
# ============================================
# 4. CLEAN EACH PRODUCT
# ============================================

cleaned_products = []

for product in products:
    p = dict(product)

    # Preserve the original category/subcategory before cleaning.
    p["category_original"] = product.get("category")
    p["subcategory_original"] = product.get("subcategory")

    # ----------------------------------------
    # Top-level text fields
    # ----------------------------------------
    for field in TEXT_FIELDS:
        p[field] = clean_text(product.get(field))

    # Category fallback: explicit unknown category.
    if p["category"] == "Not specified":
        p["category"] = "Other"

    # ----------------------------------------
    # List fields
    # ----------------------------------------
    for field in LIST_FIELDS:
        p[field] = clean_list(product.get(field))

    # ----------------------------------------
    # Dimensions
    # ----------------------------------------
    dimensions = product.get("dimensions")
    if not isinstance(dimensions, dict):
        dimensions = {}

    cleaned_dimensions = {}
    for field in ["width_mm", "depth_mm", "height_mm"]:
        cleaned_dimensions[field] = clean_numeric(dimensions.get(field))
        cleaned_dimensions[field + "_available"] = (
            cleaned_dimensions[field] > 0
        )

    p["dimensions"] = cleaned_dimensions

    # ----------------------------------------
    # Installation
    # ----------------------------------------
    installation = product.get("installation")
    if not isinstance(installation, dict):
        installation = {}

    p["installation"] = {
        "type": clean_text(installation.get("type")),
        "waste_outlet": clean_text(installation.get("waste_outlet")),
        "rough_in_mm": clean_numeric(installation.get("rough_in_mm")),
        "rough_in_available": clean_numeric(installation.get("rough_in_mm")) > 0
    }

    # ----------------------------------------
    # Electrical
    # ----------------------------------------
    electrical = product.get("electrical")
    if not isinstance(electrical, dict):
        electrical = {}

    voltage = electrical.get("voltage")
    power = clean_numeric(electrical.get("power_w"))

    # If the source explicitly says electrical_required, preserve it.
    # Otherwise infer True only when voltage or power is explicitly present.
    required = electrical.get("required")
    if is_blank(required):
        required = bool(not is_blank(voltage) or power > 0)
        electrical_required_source = "inferred_from_explicit_electrical_spec"
    else:
        required = bool(required)
        electrical_required_source = "source"

    p["electrical"] = {
        "required": required,
        "required_source": electrical_required_source,
        "voltage": clean_text(voltage),
        "power_w": power,
        "power_available": power > 0
    }

    # ----------------------------------------
    # Explicit quality flags
    # ----------------------------------------
    p["spatial_validation_possible"] = all(
        p["dimensions"][field] > 0
        for field in ["width_mm", "depth_mm", "height_mm"]
    )

    p["data_quality"] = (
        "complete_for_spatial_use"
        if p["spatial_validation_possible"]
        else "complete_with_unspecified_source_fields"
    )

    cleaned_products.append(p)

print(f"Cleaned {len(cleaned_products)} products.")

Cleaned 36 products.

In [29]:
# ============================================
# 5. VERIFY THERE ARE NO NULL/NaN VALUES
# ============================================

def find_missing_paths(obj, path=""):
    """Recursively find actual missing values in a product dictionary.

    Empty lists and empty dictionaries are VALID MongoDB values and are
    therefore not treated as missing. Only None/NaN/pd.NA and blank strings
    are considered missing.
    """
    missing = []

    if isinstance(obj, dict):
        for key, value in obj.items():
            child_path = f"{path}.{key}" if path else key
            missing.extend(find_missing_paths(value, child_path))

    elif isinstance(obj, list):
        for i, value in enumerate(obj):
            missing.extend(find_missing_paths(value, f"{path}[{i}]"))

    else:
        if is_blank(obj):
            missing.append(path)

    return missing


remaining_missing = []

for product in cleaned_products:
    problems = find_missing_paths(product)
    if problems:
        remaining_missing.append({
            "product_id": product.get("product_id"),
            "missing_paths": problems
        })

print("Products with remaining NULL/NaN/blank values:", len(remaining_missing))

if remaining_missing:
    display(pd.DataFrame(remaining_missing))
else:
    print("✓ No None, NaN, pd.NA, or blank strings remain.")

Products with remaining NULL/NaN/blank values: 0
✓ No None, NaN, pd.NA, or blank strings remain.

In [30]:
# ============================================
# 6. CREATE CLEAN INSPECTION DATAFRAME
# ============================================

clean_inspection_data = []

for p in cleaned_products:
    clean_inspection_data.append({
        "product_id": p["product_id"],
        "product_name": p["product_name"],
        "category": p["category"],
        "subcategory": p["subcategory"],
        "collection": p["collection"],
        "width_mm": p["dimensions"]["width_mm"],
        "depth_mm": p["dimensions"]["depth_mm"],
        "height_mm": p["dimensions"]["height_mm"],
        "width_available": p["dimensions"]["width_mm_available"],
        "depth_available": p["dimensions"]["depth_mm_available"],
        "height_available": p["dimensions"]["height_mm_available"],
        "rough_in_mm": p["installation"]["rough_in_mm"],
        "rough_in_available": p["installation"]["rough_in_available"],
        "installation_type": p["installation"]["type"],
        "waste_outlet": p["installation"]["waste_outlet"],
        "electrical_required": p["electrical"]["required"],
        "voltage": p["electrical"]["voltage"],
        "power_w": p["electrical"]["power_w"],
        "power_available": p["electrical"]["power_available"],
        "material": p["material"],
        "color": ", ".join(p["color"]),
        "feature_count": len(p["features"]),
        "spatial_validation_possible": p["spatial_validation_possible"],
        "data_quality": p["data_quality"]
    })

clean_inspection_df = pd.DataFrame(clean_inspection_data)

print("Clean dataset shape:", clean_inspection_df.shape)
display(clean_inspection_df.head())

Clean dataset shape: (36, 24)

,product_id,product_name,category,subcategory,collection,width_mm,depth_mm,height_mm,width_available,depth_available,...,waste_outlet,electrical_required,voltage,power_w,power_available,material,color,feature_count,spatial_validation_possible,data_quality
0,1408991-IN4-A,SPAN® Square Vessel Without Deck ( Small),Other,Not specified,Not specified,344.0,483.0,141.0,True,True,...,Not specified,False,Not specified,-1.0,False,Vitreous China,White,6,True,complete_for_spatial_use
1,29024IN-1,CHALICE ROUND VESSEL 1TAP HOLE,Vessel,Vessel,Not specified,470.0,116.0,139.0,True,True,...,Not specified,False,Not specified,-1.0,False,Vitreous China,White,5,True,complete_for_spatial_use
2,1311520-A04-D,Mica® Square 393mm Basin,BASINS / COUNTERTOP,Countertop Basin,Not specified,393.0,393.0,-1.0,True,True,...,DN32 waste without overflow,False,Not specified,-1.0,False,Ceramic,"white, honed black",3,False,complete_with_unspecified_source_fields
3,K-12927IN,Complimentary™ Hygiene Spray,Other,Not specified,Not specified,-1.0,-1.0,-1.0,False,False,...,Not specified,False,Not specified,-1.0,False,Not specified,"Polished Chrome, Vibrant® French Gold, Vibrant...",5,False,complete_with_unspecified_source_fields
4,K-1381T-S,Veil™ One-piece elongated toilet with skirted ...,Toilet,One-piece elongated toilet,Veil,-1.0,-1.0,390.0,False,False,...,Floor,False,Not specified,-1.0,False,Plastic seat,White,13,False,complete_with_unspecified_source_fields

In [31]:
# ============================================
# 7. FINAL NULL CHECK USING PANDAS
# ============================================

null_counts = clean_inspection_df.isna().sum()
blank_counts = (clean_inspection_df.astype(str).apply(lambda col: col.str.strip() == "")).sum()

final_quality_report = pd.DataFrame({
    "null_count": null_counts,
    "blank_string_count": blank_counts
})

display(final_quality_report)

assert null_counts.sum() == 0, "ERROR: Null values still exist."
assert blank_counts.sum() == 0, "ERROR: Blank strings still exist."

print("✓ FINAL CHECK PASSED — no missing values remain in the cleaned inspection dataset.")

                             null_count  blank_string_count
product_id                            0                   0
product_name                          0                   0
category                              0                   0
subcategory                           0                   0
collection                            0                   0
width_mm                              0                   0
depth_mm                              0                   0
height_mm                             0                   0
width_available                       0                   0
depth_available                       0                   0
height_available                      0                   0
rough_in_mm                           0                   0
rough_in_available                    0                   0
installation_type                     0                   0
waste_outlet                          0                   0
electrical_required                   0                   0
voltage                               0                   0
power_w                               0                   0
power_available                       0                   0
material                              0                   0
color                                 0                   0
feature_count                         0                   0
spatial_validation_possible           0                   0
data_quality                          0                   0

✓ FINAL CHECK PASSED — no missing values remain in the cleaned inspection dataset.

In [32]:
# ============================================
# 8. SAVE CLEANED DATASET TO CSV
# ============================================

clean_csv_path = Path("kohler_cleaned_products.csv")
clean_inspection_df.to_csv(clean_csv_path, index=False)

print("Cleaned CSV saved to:")
print(clean_csv_path.resolve())

Cleaned CSV saved to:
C:\Users\Abhist\Desktop\KOHLER\scripts\kohler_cleaned_products.csv

In [33]:
# ============================================
# 9. REPLACE PRODUCTS COLLECTION WITH CLEAN DATA
# ============================================

# The backup created earlier remains untouched.
# This cell updates only the main products collection.

products_collection.delete_many({})

if cleaned_products:
    products_collection.insert_many(cleaned_products)

print(f"✓ MongoDB updated with {len(cleaned_products)} cleaned products.")

✓ MongoDB updated with 36 cleaned products.

In [34]:
# ============================================
# 10. VERIFY MONGODB AFTER CLEANING
# ============================================

mongo_products = list(products_collection.find({}, {"_id": 0}))

mongo_missing = []

for product in mongo_products:
    problems = find_missing_paths(product)

    if problems:
        mongo_missing.append({
            "product_id": product.get("product_id", "Unknown"),
            "missing_paths": problems
        })

print("MongoDB product count:", len(mongo_products))
print("MongoDB products with NULL/NaN/blank values:", len(mongo_missing))

if mongo_missing:
    print("\nProblematic MongoDB documents:")
    display(pd.DataFrame(mongo_missing))

    # Do not silently continue when a real missing value exists.
    raise AssertionError(
        "ERROR: NULL/NaN/blank values remain in MongoDB. "
        "See the table above for the exact fields."
    )

print("✓ MongoDB CLEANING VERIFIED — no NULL/NaN/blank values remain.")

MongoDB product count: 36
MongoDB products with NULL/NaN/blank values: 0
✓ MongoDB CLEANING VERIFIED — no NULL/NaN/blank values remain.

## Important interpretation of `-1`

For numeric specifications, `-1` means **the source data did not provide that specification**. It is deliberately not replaced with `0` or a guessed dimension.

Use the availability flags before spatial calculations:

```python
if product["dimensions"]["depth_mm_available"]:
    # Safe to use depth_mm for a spatial calculation
else:
    # Do not use the unknown depth as a real measurement
```

The cleaning process guarantees that actual database NULL/NaN/blank values are removed.

**Note:** Empty lists (`[]`) and empty dictionaries (`{}`) are valid MongoDB values and are **not** considered missing. For example, an empty `validation_problems` list simply means no validation problems were recorded.