In [1]:
# Cell 2 — Imports

import os
import json
from pathlib import Path
from typing import Optional, List

from dotenv import load_dotenv
from pydantic import BaseModel, Field

from langchain_community.document_loaders import PyPDFLoader
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate

from pymongo import MongoClient
import pymupdf
import pandas as pd

print("Imports completed.")

C:\Users\Abhist\AppData\Local\Temp\ipykernel_18932\637097953.py:11: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFLoader

Imports completed.

In [2]:
# Cell 3 — Load API key

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

if not GROQ_API_KEY:
    raise ValueError(
        "GROQ_API_KEY not found. "
        "Make sure your .env file contains GROQ_API_KEY=your_key"
    )

print("Groq API key loaded successfully.")

Groq API key loaded successfully.

In [4]:
# Cell 4 — Configure the 51-PDF input folder

# IMPORTANT:
# Use Path(), not a normal string, because the notebook uses
# .exists(), .is_dir(), .glob(), and .resolve().

PDF_FOLDER = Path(r"C:\Users\Abhist\Desktop\KOHLER\kohler_pdfs")

if not PDF_FOLDER.exists():
    raise FileNotFoundError(
        f"PDF folder not found: {PDF_FOLDER.resolve()}\n"
        "Check that the folder path is correct."
    )

if not PDF_FOLDER.is_dir():
    raise NotADirectoryError(
        f"The specified path is not a folder: {PDF_FOLDER.resolve()}"
    )

# Find both .pdf and .PDF files
pdf_files = sorted(
    list(PDF_FOLDER.glob("*.pdf")) +
    list(PDF_FOLDER.glob("*.PDF"))
)

# Remove duplicates if a filesystem is case-insensitive
pdf_files = list(dict.fromkeys(pdf_files))

print(f"PDF folder: {PDF_FOLDER.resolve()}")
print(f"PDF files found: {len(pdf_files)}")

if len(pdf_files) != 51:
    print(f"WARNING: Expected 51 PDFs, but found {len(pdf_files)}.")
else:
    print("✓ All 51 KOHLER PDFs found successfully.")

PDF folder: C:\Users\Abhist\Desktop\KOHLER\kohler_pdfs
PDF files found: 51
✓ All 51 KOHLER PDFs found successfully.

In [5]:
# Cell 5 — Product data schema

class Dimensions(BaseModel):
    width_mm: Optional[float] = None
    depth_mm: Optional[float] = None
    height_mm: Optional[float] = None


class Installation(BaseModel):
    type: Optional[str] = None
    waste_outlet: Optional[str] = None
    rough_in_mm: Optional[float] = None


class Electrical(BaseModel):
    required: Optional[bool] = None
    voltage: Optional[str] = None
    power_w: Optional[float] = None


class Product(BaseModel):
    product_id: Optional[str] = None
    product_name: Optional[str] = None
    category: Optional[str] = None
    subcategory: Optional[str] = None
    collection: Optional[str] = None

    dimensions: Dimensions = Field(default_factory=Dimensions)
    installation: Installation = Field(default_factory=Installation)
    electrical: Electrical = Field(default_factory=Electrical)

    features: List[str] = Field(default_factory=list)
    color: List[str] = Field(default_factory=list)
    material: Optional[str] = None


print("Product schema created.")

Product schema created.

In [6]:
# Cell 6 — Initialize Groq LLM

llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0,
    api_key=GROQ_API_KEY
)

print("Groq LLM initialized.")

Groq LLM initialized.

In [7]:
# Cell 7 — Extraction prompt

prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        '''
You are a product data extraction system for a KOHLER bathroom product catalog.

Your task is to extract structured information from a KOHLER product
specification document.

IMPORTANT RULES:

1. Extract ONLY information explicitly present in the provided document.
2. NEVER invent or guess information.
3. If information is not available, return null.
4. Preserve the product/model number exactly as written.
5. Convert dimensions to millimetres when the conversion is unambiguous.
6. Convert power to watts when the conversion is unambiguous.
7. Extract product features explicitly mentioned in the document.
8. Keep installation information separate from product features.
9. Extract electrical requirements only when explicitly stated.
10. Extract the product colour when explicitly stated, including values such as
    White, Polished Chrome, Matte Black, etc.
11. Do NOT infer product price.
12. Do NOT infer aesthetic or theme scores.
13. Do NOT decide whether the product fits in a bathroom.
14. Do NOT make recommendations.
15. Do NOT use outside knowledge.
16. If a value cannot be confidently extracted from the document, return null.
17. Pay special attention to technical specifications and dimension information
    written as text.
18. Do not confuse width, depth, and height.
19. If the document gives dimensions but their orientation is not clear enough
    to assign them safely to width/depth/height, do not guess.

Return the information according to the Product schema.
'''
    ),
    (
        "human",
        '''
Extract the product information from the following KOHLER specification document:

---------------- DOCUMENT ----------------

{document}

---------------- END DOCUMENT ----------------
'''
    )
])

print("Extraction prompt created.")

Extraction prompt created.

In [8]:
# Cell 8 — Create structured-output Groq chain

structured_llm = llm.with_structured_output(Product)

chain = prompt | structured_llm

print("Structured extraction chain created.")

Structured extraction chain created.

In [9]:
# Cell 9 — Extract text from a PDF

def extract_pdf_text(pdf_path):
    '''
    Extract selectable text from all pages of a PDF.
    '''
    loader = PyPDFLoader(str(pdf_path))
    pages = loader.load()

    text = "\n".join(
        doc.page_content
        for doc in pages
    )

    return text


print("PDF text extraction function ready.")

PDF text extraction function ready.

In [10]:
# Cell 10 — Test PDF text extraction

if len(pdf_files) == 0:
    raise ValueError("No PDF files found.")

test_pdf = pdf_files[0]

test_text = extract_pdf_text(test_pdf)

print("Test PDF:", test_pdf.name)
print("Extracted characters:", len(test_text))
print()
print(test_text[:3000])

Test PDF: 1408991-IN4.pdf
Extracted characters: 2676

1408991-IN4-A

Features
• Ergonomic and Straight line design suitable for compact
 rooms with deck space.
• Easy installation as it requires counter cutting to
 accommodate drain only.
• Optimum Depth to contain Splashes.
•  Above counter without faucet deck.
• Only drain cutting(no profile cutting required).
Product Details
• Material: Vitreous China
• Overflow: Without Overflow Hole
Recommended Accessories
•  Bottle Trap (75823IN-**).
•  Compatible Drain (20746IN-**).
Code DescriptionColour
0 White
Available Colour/Finishes
Colour tiles intended for reference only.
Customer Care: 1800-103-2244 (Toll Free) & +91-124-4319685 / 86
Kohler Co. reserves the right to make revisions without notice to product speciﬁcations.
For the most current Speciﬁcation Sheet, go to www.kohler.co.in
SPAN®
Square Vessel Without Deck ( Small)
K-31459IN
KOHLER® Ten-Year Limited Warranty
See website for detailed warranty information
www.kohler.co.in/warranty
**-Finish code must be specified when ordering.
SKU Codes Description
20070IN-4-** Aleo Pillar Tap, Tall
72275IN-4-** Aleo Tall Lav Faucet W/ Drain
72326IN-4-** Aleo+ Pillar Tap, Tall
72312IN-4-** Aleo+ Tall Lav Faucet W/O Drain
99452IN-4-** Kumin Tall Pillar Tap
98827IN-4ND-** Kumin SC Tall Lav. Faucet W/O Drain
74028IN-4-** Taut™ Tall Pillar Tap
74013IN-4-** Taut™ SC Tall Lav Faucet W Drain
22538IN-4-** Hone ® Tall Pillar Tap
22534IN-4ND-** Hone ® SC Tall Lav Faucet W/O Drain
26042IN-4-** Parallel™/uni00A0Tall Pillar Tap
26040IN-4ND-** Parallel™ SC Tall Lav W/O Drain
23482IN-4-** Vive Sc Tall Lav Faucet WO Drain
23472IN-4ND-** July Sc Tall Lav Faucet Without Drain
24847IN-4-** July Tall Pillar Lavatory Faucet
1408991-IN4-A
Customer Care: 1800-103-2244 (Toll Free) & +91-124-4319685 / 86
Kohler Co. reserves the right to make revisions without notice to product speciﬁcations.
For the most current Speciﬁcation Sheet, go to www.kohler.co.in
SPAN®
Square Vessel Without Deck ( Small)
K-31459IN
Technical Specification
All product dimensions are nominal.
1394539-IN7
Lav area
Above CounterInstallation
Drain hole
Template
Lavatory configuration Single
Length: 19” (48.3)
Width: 13 9/16” (34.4)
Height: 5 9/16”(14.1)
Ø1 3/4” (4.4cm)
Notes
Install this product according to the installation
guide.
Choose a faucet that will provide adequate
clearance and will direct the water stream to the
center of the bathroom sink.
NOTICE: Drain cutting should be done using the
cut-out template provided with the product.
Kohler is not responsible for any cutout errors.
13 9/16” (34.4)
19” (48.3)
5 9/16”
(14.1)
33 7/16” (85)
1 3/4”(4.4)
Floor
Waste
Outlet
Hot
Cold5 15/16”(15)
21 5/8” (55)
19 11/16” (50)
4 3/4”
(12.1)

In [11]:
# Cell 11 — Extract one product using Groq

def extract_product_from_text(pdf_path):
    '''
    Extract one structured Product object from one PDF.
    '''
    text = extract_pdf_text(pdf_path)

    if not text.strip():
        raise ValueError(
            f"No selectable text found in PDF: {pdf_path.name}"
        )

    product = chain.invoke({
        "document": text
    })

    return product


test_product = extract_product_from_text(test_pdf)

print(test_product.model_dump_json(indent=2))

{
  "product_id": "1408991-IN4-A",
  "product_name": "SPAN® Square Vessel Without Deck ( Small)",
  "category": null,
  "subcategory": null,
  "collection": "SPAN®",
  "dimensions": {
    "width_mm": 344.0,
    "depth_mm": 483.0,
    "height_mm": 141.0
  },
  "installation": {
    "type": "Counter cutting",
    "waste_outlet": null,
    "rough_in_mm": null
  },
  "electrical": {
    "required": null,
    "voltage": null,
    "power_w": null
  },
  "features": [
    "Ergonomic and Straight line design suitable for compact rooms with deck space.",
    "Easy installation as it requires counter cutting to accommodate drain only.",
    "Optimum Depth to contain Splashes.",
    "Above counter without faucet deck.",
    "Only drain cutting (no profile cutting required).",
    "Without Overflow Hole"
  ],
  "color": [
    "White"
  ],
  "material": "Vitreous China"
}

In [12]:
# Cell 12 — Validate one extracted product

def validate_product(product):
    '''
    Check important fields without modifying the extracted product.
    '''
    problems = []

    if not product.product_id:
        problems.append("Missing product ID")

    if not product.product_name:
        problems.append("Missing product name")

    if not product.category:
        problems.append("Missing category")

    if product.dimensions.width_mm is None:
        problems.append("Missing width")

    if product.dimensions.depth_mm is None:
        problems.append("Missing depth")

    if product.dimensions.height_mm is None:
        problems.append("Missing height")

    return problems


test_problems = validate_product(test_product)

if test_problems:
    print("Validation warnings:")
    for problem in test_problems:
        print("-", problem)
else:
    print("✓ Product passed validation.")

Validation warnings:
- Missing category

In [13]:
# Cell 13 — MongoDB connection

# Start your local MongoDB server before running this cell.
# MongoDB Compass connects to the same server using:
# mongodb://localhost:27017

MONGO_URI = "mongodb://localhost:27017"

try:
    mongo_client = MongoClient(
        MONGO_URI,
        serverSelectionTimeoutMS=5000
    )

    # Test the connection
    mongo_client.admin.command("ping")

    db = mongo_client["kohler_ai_bathroom"]
    products_collection = db["products"]

    # Product IDs should be unique
    products_collection.create_index(
        "product_id",
        unique=True
    )

    print("✓ MongoDB connected successfully.")
    print("Database: kohler_ai_bathroom")
    print("Collection: products")

except Exception as e:
    raise ConnectionError(
        "Could not connect to MongoDB at mongodb://localhost:27017. "
        "Make sure your local MongoDB server is running."
    ) from e

✓ MongoDB connected successfully.
Database: kohler_ai_bathroom
Collection: products

In [14]:
# Cell 14 — Convert Product object to MongoDB document

def product_to_document(product, pdf_path, extraction_status="success", validation_problems=None):
    '''
    Convert the Pydantic Product object into a MongoDB-ready dictionary.
    '''
    document = product.model_dump()

    document["source_pdf"] = pdf_path.name
    document["source_type"] = "KOHLER specification PDF"
    document["extraction_method"] = "Groq text extraction"
    document["extraction_status"] = extraction_status
    document["validation_problems"] = validation_problems or []

    return document


test_document = product_to_document(
    test_product,
    test_pdf,
    validation_problems=test_problems
)

print(json.dumps(test_document, indent=2, default=str))

{
  "product_id": "1408991-IN4-A",
  "product_name": "SPAN\u00ae Square Vessel Without Deck ( Small)",
  "category": null,
  "subcategory": null,
  "collection": "SPAN\u00ae",
  "dimensions": {
    "width_mm": 344.0,
    "depth_mm": 483.0,
    "height_mm": 141.0
  },
  "installation": {
    "type": "Counter cutting",
    "waste_outlet": null,
    "rough_in_mm": null
  },
  "electrical": {
    "required": null,
    "voltage": null,
    "power_w": null
  },
  "features": [
    "Ergonomic and Straight line design suitable for compact rooms with deck space.",
    "Easy installation as it requires counter cutting to accommodate drain only.",
    "Optimum Depth to contain Splashes.",
    "Above counter without faucet deck.",
    "Only drain cutting (no profile cutting required).",
    "Without Overflow Hole"
  ],
  "color": [
    "White"
  ],
  "material": "Vitreous China",
  "source_pdf": "1408991-IN4.pdf",
  "source_type": "KOHLER specification PDF",
  "extraction_method": "Groq text extraction",
  "extraction_status": "success",
  "validation_problems": [
    "Missing category"
  ]
}

In [15]:
# Cell 15 — Upsert one product into MongoDB

def upsert_product(document):
    '''
    Insert a product or update it if the same product_id already exists.

    This prevents duplicate documents when the notebook is rerun.
    '''
    product_id = document.get("product_id")

    if not product_id:
        raise ValueError(
            "Cannot upsert product because product_id is missing."
        )

    result = products_collection.update_one(
        {"product_id": product_id},
        {"$set": document},
        upsert=True
    )

    return result


result = upsert_product(test_document)

print("Test product saved to MongoDB.")
print("Matched:", result.matched_count)
print("Modified:", result.modified_count)
print("Upserted ID:", result.upserted_id)

Test product saved to MongoDB.
Matched: 0
Modified: 0
Upserted ID: 6aa95896c877dad10aa25e69

## Process all 51 PDFs

The following cell processes every PDF individually.

For each PDF:

1. Extract PDF text.
2. Send the text to Groq.
3. Convert the response into the `Product` schema.
4. Validate the extracted information.
5. Add source metadata.
6. Upsert the product into MongoDB.
7. Record success or failure.

A failure on one PDF will **not stop the remaining PDFs**.

In [16]:
# Cell 16 — Process all PDFs

all_results = []
failed_pdfs = []

print(f"Starting extraction for {len(pdf_files)} PDFs...")
print("=" * 70)

for index, pdf_path in enumerate(pdf_files, start=1):

    print(f"[{index}/{len(pdf_files)}] Processing: {pdf_path.name}")

    try:
        product = extract_product_from_text(pdf_path)

        validation_problems = validate_product(product)

        document = product_to_document(
            product,
            pdf_path,
            extraction_status="success",
            validation_problems=validation_problems
        )

        upsert_product(document)

        all_results.append({
            "pdf": pdf_path.name,
            "product_id": product.product_id,
            "product_name": product.product_name,
            "category": product.category,
            "status": "success",
            "validation_problems": "; ".join(validation_problems)
        })

        if validation_problems:
            print("  ✓ Extracted with validation warnings.")
        else:
            print("  ✓ Extracted successfully.")

    except Exception as e:

        error_message = str(e)

        print(f"  ✗ FAILED: {error_message}")

        failed_pdfs.append({
            "pdf": pdf_path.name,
            "error": error_message
        })

        all_results.append({
            "pdf": pdf_path.name,
            "product_id": None,
            "product_name": None,
            "category": None,
            "status": "failed",
            "validation_problems": error_message
        })

print("=" * 70)
print("Extraction completed.")
print(f"Successful PDFs: {len(pdf_files) - len(failed_pdfs)}")
print(f"Failed PDFs: {len(failed_pdfs)}")

Starting extraction for 51 PDFs...
======================================================================
[1/51] Processing: 1408991-IN4.pdf
  ✓ Extracted with validation warnings.
[2/51] Processing: 29024IN-1_Chalice w deck vessel.pdf
  ✓ Extracted successfully.
[3/51] Processing: 90011T.pdf
  ✓ Extracted with validation warnings.
[4/51] Processing: K-12925IN_spec_IN_Kohler_en.pdf
  ✗ FAILED: Error code: 400 - {'error': {'message': 'Tool call validation failed: tool call validation failed: parameters for tool Product did not match schema: errors: [`/dimensions`: expected object, but got null, `/electrical`: expected object, but got null]', 'type': 'invalid_request_error', 'code': 'tool_use_failed', 'failed_generation': '{"name": "Product", "arguments": {\n  "category": "Faucet",\n  "collection": "Complementary™",\n  "product_id": "K-12925IN",\n  "product_name": "Complementary™ Health faucet, 11.7 lpm",\n  "subcategory": "Health faucet",\n  "color": ["Polished Chrome", "Vibrant® French Gold", "Vibrant Rose Gold"],\n  "dimensions": null,\n  "electrical": null,\n  "features": [\n    "Includes 39.37 inch (1000 mm) hose and wall-mount holder",\n    "3.09 gpm (11.7 lpm) flow rate at 43.51 psi (3 bar)"\n  ],\n  "installation": {\n    "type": "Wall-mount",\n    "rough_in_mm": null,\n    "waste_outlet": null\n  },\n  "material": null\n}}'}}
[5/51] Processing: K-12927IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[6/51] Processing: K-1381T-S_spec_CN_Kohler_en.pdf
  ✗ FAILED: Error code: 400 - {'error': {'message': 'Tool call validation failed: tool call validation failed: parameters for tool Product did not match schema: errors: [`/electrical`: expected object, but got null]', 'type': 'invalid_request_error', 'code': 'tool_use_failed', 'failed_generation': '{"name": "Product", "arguments": {\n  "category": "Toilet",\n  "collection": "Veil",\n  "color": ["White"],\n  "dimensions": {\n    "height_mm": 390,\n    "depth_mm": null,\n    "width_mm": null\n  },\n  "electrical": null,\n  "features": [\n    "One-piece toilets integrate the tank and bowl into a seamless, easy-to-clean design",\n    "Elongated bowl offers added room and comfort",\n    "Rim-to-floor height: 15.35 inches (390 mm)",\n    "Dual-flush offers a choice of 0.8 or 1.28 gpf (3.0 or 4.5 lpf)",\n    "Washdown flushing system",\n    "Left-hand Polished Chrome trip lever",\n    "52 mm (2 inch) fully glazed trapway",\n    "Fully skirted trapway simplifies cleaning",\n    "Seat and lid included",\n    "Quiet-Close™ functionality to prevent seat from slamming",\n    "Quick-Attach™ hardware for fast and secure installation",\n    "Quick-Release™ functionality allows seat to be removed easily from toilet for convenient cleaning",\n    "Coordinates with other products in the Veil collection",\n    "Compatible with C3™ and PureWash™ electronic bidet seats (sold separately)"\n  ],\n  "installation": {\n    "rough_in_mm": 305,\n    "type": "Floor-mount",\n    "waste_outlet": "Floor"\n  },\n  "material": "Plastic seat",\n  "product_id": "K-1381T-S",\n  "product_name": "Veil™ One-piece elongated toilet with skirted trapway, dual-flush",\n  "subcategory": "One-piece elongated toilet"\n}}'}}
[7/51] Processing: K-1381T-S_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[8/51] Processing: K-15848T_spec_IN_Kohler_en.pdf
  ✗ FAILED: Error code: 400 - {'error': {'message': 'Tool call validation failed: tool call validation failed: parameters for tool Product did not match schema: errors: [`/electrical`: expected object, but got null]', 'type': 'invalid_request_error', 'code': 'tool_use_failed', 'failed_generation': '{"name": "Product", "arguments": {\n  "category": "Bath",\n  "collection": "Reach™",\n  "product_name": "Reach™ drop-in bath",\n  "product_id": "K-15848T",\n  "subcategory": "Drop-in Bath",\n  "color": ["White"],\n  "material": "Acrylic",\n  "dimensions": {\n    "width_mm": 1700,\n    "depth_mm": 700,\n    "height_mm": 460\n  },\n  "features": [\n    "Rectangular basin creates a spacious bathing experience",\n    "Drop-in design creates a seamless bathroom aesthetic",\n    "Round overflow",\n    "12-11/16\\" (322 mm) soaking depth",\n    "Integral lumbar support",\n    "Easy-to-clean, durable high-gloss finish",\n    "Lumbar angle 30°"\n  ],\n  "installation": {\n    "type": "Drop-in",\n    "rough_in_mm": null,\n    "waste_outlet": null\n  },\n  "electrical": null\n}}'}}
[9/51] Processing: K-17629T-NS_spec_CN_Kohler_en (1).pdf
  ✗ FAILED: Error code: 400 - {'error': {'message': 'Tool call validation failed: tool call validation failed: parameters for tool Product did not match schema: errors: [`/color`: expected array, but got null]', 'type': 'invalid_request_error', 'code': 'tool_use_failed', 'failed_generation': '{"name": "Product", "arguments": {\n  "category": "Toilet",\n  "collection": "Ove™",\n  "color": null,\n  "dimensions": {\n    "height_mm": 390,\n    "width_mm": null,\n    "depth_mm": null\n  },\n  "electrical": {\n    "power_w": null,\n    "required": null,\n    "voltage": null\n  },\n  "features": [\n    "One-piece toilets integrate the tank and bowl into a seamless, easy-to-clean design",\n    "Round-front bowl offers an ideal solution for smaller bathrooms and powder rooms",\n    "Rim-to-floor height: 15.35 inches (390 mm)",\n    "Top-mount Polished Chrome dual-flush button offers a choice of 0.8 or 1.6 gpf (3.0 or 6.0 lpf)",\n    "2.3 inch (58 mm) fully glazed trapway",\n    "Fully skirted trapway simplifies cleaning",\n    "Coordinates with other products in the Ove™ collection",\n    "Compatible with C3™ toilet seats and the Ove™ Quiet-Close toilet seat and lid (sold separately)"\n  ],\n  "installation": {\n    "rough_in_mm": 185,\n    "type": "Floor-mount",\n    "waste_outlet": "Floor"\n  },\n  "material": null,\n  "product_id": "K-17629T-NS",\n  "product_name": "Ove™ One-piece round-front toilet with skirted trapway, dual-flush",\n  "subcategory": "One-piece round-front toilet"\n}}'}}
[10/51] Processing: K-17629T-NS_spec_CN_Kohler_en.pdf
  ✗ FAILED: Error code: 400 - {'error': {'message': 'Tool call validation failed: tool call validation failed: parameters for tool Product did not match schema: errors: [`/color`: expected array, but got null]', 'type': 'invalid_request_error', 'code': 'tool_use_failed', 'failed_generation': '{"name": "Product", "arguments": {\n  "category": "Toilet",\n  "collection": "Ove™",\n  "product_id": "K-17629T-NS",\n  "product_name": "Ove™ One-piece round-front toilet with skirted trapway, dual-flush",\n  "subcategory": "One-piece toilet",\n  "color": null,\n  "dimensions": {\n    "height_mm": 390,\n    "width_mm": null,\n    "depth_mm": null\n  },\n  "electrical": {\n    "required": false,\n    "power_w": null,\n    "voltage": null\n  },\n  "features": [\n    "One-piece toilets integrate the tank and bowl into a seamless, easy-to-clean design",\n    "Round-front bowl offers an ideal solution for smaller bathrooms and powder rooms",\n    "Top-mount Polished Chrome dual-flush button offers a choice of 0.8 or 1.6 gpf (3.0 or 6.0 lpf)",\n    "2.3 inch (58 mm) fully glazed trapway",\n    "Fully skirted trapway simplifies cleaning",\n    "Coordinates with other products in the Ove™ collection",\n    "Compatible with C3™ toilet seats and the Ove™ Quiet-Close toilet seat and lid (sold separately)",\n    "Flush type: Washdown",\n    "Trap passageway: 2\\" (51 mm)",\n    "Rim to water surface: 9-7/8\\" (251 mm)"\n  ],\n  "installation": {\n    "rough_in_mm": 185,\n    "type": "Floor-mount",\n    "waste_outlet": "Floor"\n  },\n  "material": null\n}}'}}
[11/51] Processing: K-17629T-NS_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[12/51] Processing: K-17660T-M_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[13/51] Processing: K-1851IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[14/51] Processing: K-1853IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[15/51] Processing: K-1855IN_spec_IN_Kohler_en.pdf
  ✗ FAILED: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01kvzjzwdmftpb78y72tp6e99t` service tier `on_demand` on tokens per minute (TPM): Limit 8000, Used 5952, Requested 2142. Please try again in 705ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
[16/51] Processing: K-21226IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[17/51] Processing: K-2200IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[18/51] Processing: K-2215IN-2_spec_IN_Kohler_en.pdf
  ✗ FAILED: Error code: 400 - {'error': {'message': 'Tool call validation failed: tool call validation failed: parameters for tool Product did not match schema: errors: [`/dimensions`: expected object, but got null, `/electrical`: expected object, but got null]', 'type': 'invalid_request_error', 'code': 'tool_use_failed', 'failed_generation': '{"name": "Product", "arguments": {\n  "category": "Sink",\n  "collection": "Ladena™",\n  "product_name": "Ladena™ 581 mm rectangular undercounter bathroom sink",\n  "product_id": "K-2215IN-2",\n  "color": ["White", "Black"],\n  "material": "Vitreous china",\n  "features": [\n    "Rectangular basin with curved bottom",\n    "No faucet holes; requires wall- or deck-mount faucet",\n    "Offset drain increases workspace in the sink and storage space underneath",\n    "With overflow",\n    "Basin configuration: Single Bowl"\n  ],\n  "installation": {\n    "type": "Undercounter"\n  },\n  "dimensions": null,\n  "electrical": null,\n  "subcategory": null,\n  "collection": "Ladena™"\n}}'}}
[19/51] Processing: K-23486IN-4ND_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[20/51] Processing: K-23966IN-4ND_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[21/51] Processing: K-23967IN-4ND_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[22/51] Processing: K-23975IN-4ND_spec_IN_Kohler_en.pdf
  ✗ FAILED: Error code: 400 - {'error': {'message': 'Tool call validation failed: tool call validation failed: parameters for tool Product did not match schema: errors: [`/electrical`: expected object, but got null, `/dimensions`: expected object, but got null]', 'type': 'invalid_request_error', 'code': 'tool_use_failed', 'failed_generation': '{"name": "Product", "arguments": {\n  "category": "Faucet",\n  "collection": "VIVE",\n  "color": ["Polished Chrome", "Vibrant French Gold", "Matte Black", "Vibrant Rose Gold"],\n  "dimensions": null,\n  "electrical": null,\n  "features": [\n    "Single handle controls both on/off activation and temperature setting",\n    "Spout reach of 6-5/8\\" (168 mm)",\n    "Maximum flow rate of 1.5 gpm (5.5 lpm) at 43.5 psi (3.0 bar)",\n    "Premium metal construction for durability and reliability",\n    "KOHLER finishes resist corrosion and tarnishing"\n  ],\n  "installation": {\n    "type": "Wall-mount",\n    "waste_outlet": "Drain sold separately"\n  },\n  "material": "Premium metal",\n  "product_id": "K-23975IN-4ND",\n  "product_name": "KOHLER VIVE® Wall-mount bathroom sink faucet, 5.5 lpm",\n  "subcategory": "Wall-mount bathroom sink faucet"\n}}'}}
[23/51] Processing: K-25316IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[24/51] Processing: K-25318IN_spec_IN_Kohler_en.pdf
  ✗ FAILED: Error code: 400 - {'error': {'message': 'Tool call validation failed: tool call validation failed: parameters for tool Product did not match schema: errors: [`/electrical`: expected object, but got null, `/dimensions`: expected object, but got null]', 'type': 'invalid_request_error', 'code': 'tool_use_failed', 'failed_generation': '{"name": "Product", "arguments": {\n  "category": "Sink",\n  "subcategory": "Vessel",\n  "product_id": "K-25318IN",\n  "product_name": "Span™ 471 mm oval vessel bathroom sink with glazed underside, no overflow",\n  "material": "Vitreous china",\n  "color": ["White"],\n  "dimensions": null,\n  "electrical": null,\n  "features": [\n    "Minimalist design with thin, rounded edges",\n    "Oval basin",\n    "Integrated faucet deck provides additional water containment",\n    "Single faucet hole at deck center",\n    "Without overflow",\n    "Glazed underside offers beauty from all angles"\n  ],\n  "installation": {\n    "type": "Vessel",\n    "rough_in_mm": null,\n    "waste_outlet": null\n  }\n}}'}}
[25/51] Processing: K-2661IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[26/51] Processing: K-27477IN-4ND_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[27/51] Processing: K-27480IN-4ND_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[28/51] Processing: K-27484IN-4_spec_IN_Kohler_en.pdf
  ✗ FAILED: Error code: 400 - {'error': {'message': 'Tool call validation failed: tool call validation failed: parameters for tool Product did not match schema: errors: [`/dimensions`: expected object, but got null, `/electrical`: expected object, but got null]', 'type': 'invalid_request_error', 'code': 'tool_use_failed', 'failed_generation': '{"name": "Product", "arguments": {\n  "category": "Faucet",\n  "collection": "Fore Tri®",\n  "color": ["Polished Chrome"],\n  "dimensions": null,\n  "electrical": null,\n  "features": [\n    "Sleek and contemporary design",\n    "Single handle provides on/off activation and volume control",\n    "For use with cold water line only",\n    "3.85 inch (98 mm) spout reach",\n    "3.32 inch (84 mm) spout height",\n    "Aerated flow",\n    "4.22 gpm (16.0 lpm) maximum flow rate at 43.5 psi (3.0 bar)",\n    "KOHLER® ceramic disc valves exceed industry longevity standards for a lifetime of durable performance",\n    "Premium metal construction for durability and reliability",\n    "KOHLER finishes resist corrosion and tarnishing"\n  ],\n  "installation": {\n    "type": "Single-hole, Deck-mount"\n  },\n  "material": "Premium metal",\n  "product_id": "K-27484IN-4",\n  "product_name": "Fore Tri® Single-handle bathroom sink faucet, cold only",\n  "subcategory": "Single-handle"\n}}'}}
[29/51] Processing: K-27485IN-4_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[30/51] Processing: K-28529IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[31/51] Processing: K-28783IN_spec_IN_Kohler_en.pdf
  ✗ FAILED: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01kvzjzwdmftpb78y72tp6e99t` service tier `on_demand` on tokens per minute (TPM): Limit 8000, Used 5594, Requested 2472. Please try again in 495ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
[32/51] Processing: K-28784IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[33/51] Processing: K-29777IN_spec_IN_Kohler_en.pdf
  ✗ FAILED: Error code: 400 - {'error': {'message': 'Tool call validation failed: tool call validation failed: parameters for tool Product did not match schema: errors: [`/color`: expected array, but got null]', 'type': 'invalid_request_error', 'code': 'tool_use_failed', 'failed_generation': '{"name": "Product", "arguments": {\n  "product_name": "Innate™ One-piece elongated smart toilet, dual-flush",\n  "product_id": "K-29777IN",\n  "category": null,\n  "subcategory": null,\n  "collection": null,\n  "color": null,\n  "dimensions": {\n    "depth_mm": null,\n    "height_mm": null,\n    "width_mm": null\n  },\n  "electrical": {\n    "required": true,\n    "voltage": "220-240 V",\n    "power_w": null\n  },\n  "features": [\n    "Compact, streamlined one-piece smart toilet with integrated personal cleansing",\n    "Compact elongated bowl offers added comfort while requiring less space",\n    "Dual-flush offers a choice of .92 or 1.32 gpf (3.5 or 5.0 lpf)",\n    "Fully skirted trapway simplifies cleaning",\n    "Quiet-Close™ elongated lid and seat prevents slamming",\n    "Stainless steel wand offers adjustable spray shape, position, water pressure, temperature, pulsate, and oscillate functions",\n    "Front and rear wash modes provide warm water for cleansing",\n    "Self-cleaning function uses UV light to automatically sanitize the wand surfaces",\n    "Motion-activated, hands-free opening/closing of cover",\n    "Bowl is automatically misted prior to use for more effective rinsing while flushing",\n    "Heated seat with adjustable temperature settings",\n    "Warm-air drying system",\n    "Automatic deodorization system",\n    "LED lighting illuminates the bowl to serve as a nightlight",\n    "Energy Save feature monitors usage and adjusts heated seat settings to save energy",\n    "Includes complete toilet and seat, supply stop valve, braided inlet supply hose, power cord, and remote control",\n    "Mounting hardware is completely concealed, giving a sleek, seamless look that is easy to clean",\n    "Automatic flushing after every use; flush can also be controlled by the remote control or backup button"\n  ],\n  "installation": {\n    "rough_in_mm": 305,\n    "type": "Floor-mount",\n    "waste_outlet": "Floor"\n  },\n  "material": null\n}}'}}
[34/51] Processing: K-33123IN-HC_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[35/51] Processing: K-3983IN-S_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[36/51] Processing: K-5373IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[37/51] Processing: K-5684IN-4ND_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[38/51] Processing: K-72298IN-4ND_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[39/51] Processing: K-72337IN-4ND_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[40/51] Processing: K-75374IN-1_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[41/51] Processing: K-75375IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[42/51] Processing: K-75377IN-4_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[43/51] Processing: K-77364IN_spec_IN_Kohler_en.pdf
  ✓ Extracted with validation warnings.
[44/51] Processing: K-8688T-S_spec_IN_Kohler_en.pdf
  ✗ FAILED: Error code: 400 - {'error': {'message': 'Tool call validation failed: tool call validation failed: parameters for tool Product did not match schema: errors: [`/electrical`: expected object, but got null]', 'type': 'invalid_request_error', 'code': 'tool_use_failed', 'failed_generation': '{"name": "Product", "arguments": {\n  "category": "Toilet",\n  "collection": null,\n  "color": ["White"],\n  "dimensions": {\n    "height_mm": 390,\n    "depth_mm": null,\n    "width_mm": null\n  },\n  "electrical": null,\n  "features": [\n    "One-piece toilets integrate the tank and bowl into a seamless, easy-to-clean design",\n    "Elongated bowl offers added room and comfort",\n    "Rim-to-floor height: 390 mm (15-3/8 inches)",\n    "1.28 gpf (4.8 lpf)",\n    "Left-hand trip lever",\n    "2.3 inch (59 mm) fully glazed trapway",\n    "Fully skirted trapway simplifies cleaning",\n    "Class Five™ canister optimizes the flow out of the tank, harnessing gravity and the natural powerful reducing cascade of water to increase the power and effectiveness of the flush",\n    "French Curve™ seat and lid included",\n    "Quiet-Close™ seat with Quick-Release™ functionality closes quietly and quickly unlatches from the toilet for easy removal and convenient cleaning"\n  ],\n  "installation": {\n    "rough_in_mm": 305,\n    "type": "Floor-mount",\n    "waste_outlet": "Floor"\n  },\n  "material": "Plastic seat",\n  "product_id": "K-8688T-S",\n  "product_name": "San Raphael Grande™",\n  "subcategory": "One-piece elongated toilet"\n}}'}}
[45/51] Processing: K-90011T_spec_IN_Kohler_en.pdf

In [17]:
# Cell 17 — Create extraction report

extraction_report = pd.DataFrame(all_results)

print("Extraction report:")
display(extraction_report)

if failed_pdfs:
    print("\nFailed PDFs:")
    display(pd.DataFrame(failed_pdfs))
else:
    print("\n✓ No PDFs failed.")

Extraction report:

,pdf,product_id,product_name,category,status,validation_problems
0,1408991-IN4.pdf,1408991-IN4-A,SPAN® Square Vessel Without Deck ( Small),NaN,success,Missing category
1,29024IN-1_Chalice w deck vessel.pdf,29024IN-1,CHALICE ROUND VESSEL 1TAP HOLE,Vessel,success,
2,90011T.pdf,1311520-A04-D,Mica® Square 393mm Basin,BASINS / COUNTERTOP,success,Missing height
3,K-12925IN_spec_IN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
4,K-12927IN_spec_IN_Kohler_en.pdf,K-12927IN,Complimentary™ Hygiene Spray,NaN,success,Missing category; Missing width; Missing depth...
5,K-1381T-S_spec_CN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
6,K-1381T-S_spec_IN_Kohler_en.pdf,K-1381T-S,Veil™ One-piece elongated toilet with skirted ...,Toilet,success,Missing width; Missing depth
7,K-15848T_spec_IN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
8,K-17629T-NS_spec_CN_Kohler_en (1).pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
9,K-17629T-NS_spec_CN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
10,K-17629T-NS_spec_IN_Kohler_en.pdf,K-17629T-NS,Ove™ One-piece round-front toilet with skirted...,Toilet,success,Missing width; Missing depth
11,K-17660T-M_spec_IN_Kohler_en.pdf,K-17660T-M,Ove™ Quiet-Close™ elongated toilet seat,Toilet Seat,success,Missing width; Missing depth; Missing height
12,K-1851IN_spec_IN_Kohler_en.pdf,K-1851IN,Brive Plus,NaN,success,Missing category; Missing width; Missing depth
13,K-1853IN_spec_IN_Kohler_en.pdf,K-1853IN,Brive Plus,NaN,success,Missing category; Missing width; Missing depth
14,K-1855IN_spec_IN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 429 - {'error': {'message': 'Rate ...
15,K-21226IN_spec_IN_Kohler_en.pdf,K-21226IN,ModernLife Edge 600 mm rectangular vessel bath...,Sink,success,Missing height
16,K-2200IN_spec_IN_Kohler_en.pdf,K-2200IN,Conical Bell™,Sink,success,Missing depth; Missing height
17,K-2215IN-2_spec_IN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
18,K-23486IN-4ND_spec_IN_Kohler_en.pdf,K-23486IN-4ND,"Parallel™ Wall-mount bathroom sink faucet, 9.0...",Faucet,success,Missing width; Missing depth; Missing height
19,K-23966IN-4ND_spec_IN_Kohler_en.pdf,K-23966IN-4ND,KOHLER VIVE® Single-handle bathroom sink fauce...,Faucet,success,Missing width; Missing depth; Missing height
20,K-23967IN-4ND_spec_IN_Kohler_en.pdf,K-23967IN-4ND,KOHLER VIVE® Tall single-handle bathroom sink ...,Faucet,success,Missing width; Missing depth; Missing height
21,K-23975IN-4ND_spec_IN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
22,K-25316IN_spec_IN_Kohler_en.pdf,K-25316IN,Span™ 537 mm rectangular vessel bathroom sink ...,Bathroom sink,success,Missing depth; Missing height
23,K-25318IN_spec_IN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
24,K-2661IN_spec_IN_Kohler_en.pdf,K-2661IN,Vox™ 413 mm square vessel bathroom sink,Bathroom sink,success,Missing height
25,K-27477IN-4ND_spec_IN_Kohler_en.pdf,K-27477IN-4ND,"Fore Tri® Single-handle bathroom sink faucet, ...",Faucet,success,Missing width; Missing depth; Missing height
26,K-27480IN-4ND_spec_IN_Kohler_en.pdf,K-27480IN-4ND,Fore Line™ Tall single-handle bathroom sink fa...,Faucet,success,Missing width; Missing depth; Missing height
27,K-27484IN-4_spec_IN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
28,K-27485IN-4_spec_IN_Kohler_en.pdf,K-27485IN-4,"Fore Line™ Single-handle bathroom sink faucet,...",Faucet,success,Missing width
29,K-28529IN_spec_IN_Kohler_en.pdf,K-28529IN,"Leap™ One-piece round-front smart toilet, dual...",Toilet,success,Missing width; Missing depth
30,K-28783IN_spec_IN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 429 - {'error': {'message': 'Rate ...
31,K-28784IN_spec_IN_Kohler_en.pdf,K-28784IN,KOHLER VIVE® 552 mm rectangular vessel bathroo...,Bathroom Sink,success,Missing width; Missing depth; Missing height
32,K-29777IN_spec_IN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
33,K-33123IN-HC_spec_IN_Kohler_en.pdf,K-33123IN-HC,KOHLER VIVE Hidden cord one-piece round-front ...,Toilet,success,Missing width; Missing depth
34,K-3983IN-S_spec_IN_Kohler_en.pdf,K-3983IN-S,Reach™ One-piece round-front toilet with skirt...,Toilet,success,Missing width; Missing depth
35,K-5373IN_spec_IN_Kohler_en.pdf,K-5373IN,Forefront™ 580 mm rectangular vessel bathroom ...,Bathroom sink,success,Missing width; Missing depth; Missing height
36,K-5684IN-4ND_spec_IN_Kohler_en.pdf,K-5684IN-4ND,"Aleo+™ Wall-mount bathroom sink faucet trim, 9...",Faucet Trim,success,Missing width; Missing depth; Missing height
37,K-72298IN-4ND_spec_IN_Kohler_en.pdf,K-72298IN-4ND,"Aleo® Tall single-handle bathroom sink faucet,...",Faucet,success,Missing width; Missing depth; Missing height
38,K-72337IN-4ND_spec_IN_Kohler_en.pdf,K-72337IN-4ND,Aleo+™ Tall single-handle bathroom sink faucet...,Faucet,success,Missing width; Missing depth; Missing height
39,K-75374IN-1_spec_IN_Kohler_en.pdf,K-75374IN-1,Forefront™ 460 mm square vessel bathroom sink ...,Bathroom sink,success,Missing height
40,K-75375IN_spec_IN_Kohler_en.pdf,K-75375IN,Forefront™ 890 mm rectangular vessel bathroom ...,Bathroom sink,success,Missing width; Missing depth
41,K-75377IN-4_spec_IN_Kohler_en.pdf,K-75377IN-4,"July™ Single-handle bathroom sink faucet, cold...",Bathroom sink faucet,success,Missing width; Missing depth; Missing height
42,K-77364IN_spec_IN_Kohler_en.pdf,K-77364IN,"Health faucet, 8.5 lpm",Faucet,success,Missing width; Missing depth; Missing height
43,K-8688T-S_spec_IN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
44,K-90011T_spec_IN_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...
45,K-97258IN-ZZ_spec_IN_Kohler_en.pdf,K-97258IN-ZZ,"Elate™ Single-function health faucet, 8.5 lpm",Faucet,success,Missing width; Missing depth; Missing height
46,K-97258IN_spec_IN_Kohler_en.pdf,K-97258IN,"Elate™ Single-function health faucet, 8.5 lpm",Faucet,success,Missing width; Missing depth; Missing height
47,K-97347T-4_spec_GPS_Kohler_en.pdf,K-97347T-4,Avid™ Tall Single-handle bathroom sink faucet,Faucet,success,Missing width; Missing depth; Missing height
48,K-98100IN-ZZ_spec_IN_Kohler_en.pdf,K-98100IN-ZZ,"Beam™ Health faucet, 10 lpm",Faucet,success,Missing width; Missing depth; Missing height
49,K-98100IN_spec_IN_Kohler_en.pdf,K-98100IN,"Cuff™ Single-function health faucet, 11.5 lpm",Faucet,success,Missing width; Missing depth; Missing height
50,K-98930X-1_spec_GPS_Kohler_en.pdf,NaN,NaN,NaN,failed,Error code: 400 - {'error': {'message': 'Tool ...

Failed PDFs:

,pdf,error
0,K-12925IN_spec_IN_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...
1,K-1381T-S_spec_CN_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...
2,K-15848T_spec_IN_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...
3,K-17629T-NS_spec_CN_Kohler_en (1).pdf,Error code: 400 - {'error': {'message': 'Tool ...
4,K-17629T-NS_spec_CN_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...
5,K-1855IN_spec_IN_Kohler_en.pdf,Error code: 429 - {'error': {'message': 'Rate ...
6,K-2215IN-2_spec_IN_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...
7,K-23975IN-4ND_spec_IN_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...
8,K-25318IN_spec_IN_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...
9,K-27484IN-4_spec_IN_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...
10,K-28783IN_spec_IN_Kohler_en.pdf,Error code: 429 - {'error': {'message': 'Rate ...
11,K-29777IN_spec_IN_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...
12,K-8688T-S_spec_IN_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...
13,K-90011T_spec_IN_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...
14,K-98930X-1_spec_GPS_Kohler_en.pdf,Error code: 400 - {'error': {'message': 'Tool ...

In [18]:
# Cell 18 — Save extraction report as CSV

report_path = Path("kohler_extraction_report.csv")

extraction_report.to_csv(
    report_path,
    index=False
)

print(f"Report saved to: {report_path.resolve()}")

Report saved to: C:\Users\Abhist\Desktop\KOHLER\scripts\kohler_extraction_report.csv

In [19]:
# Cell 19 — Verify MongoDB contents

total_documents = products_collection.count_documents({})

print(f"Products currently stored in MongoDB: {total_documents}")

print("\nSample documents:")

sample_documents = list(
    products_collection.find(
        {},
        {
            "_id": 0,
            "product_id": 1,
            "product_name": 1,
            "category": 1,
            "dimensions": 1,
            "source_pdf": 1
        }
    ).limit(5)
)

for document in sample_documents:
    print(json.dumps(document, indent=2, default=str))

Products currently stored in MongoDB: 36

Sample documents:
{
  "product_id": "1408991-IN4-A",
  "category": null,
  "dimensions": {
    "width_mm": 344.0,
    "depth_mm": 483.0,
    "height_mm": 141.0
  },
  "product_name": "SPAN\u00ae Square Vessel Without Deck ( Small)",
  "source_pdf": "1408991-IN4.pdf"
}
{
  "product_id": "29024IN-1",
  "category": "Vessel",
  "dimensions": {
    "width_mm": 470.0,
    "depth_mm": 116.0,
    "height_mm": 139.0
  },
  "product_name": "CHALICE ROUND VESSEL 1TAP HOLE",
  "source_pdf": "29024IN-1_Chalice w deck vessel.pdf"
}
{
  "product_id": "1311520-A04-D",
  "category": "BASINS / COUNTERTOP",
  "dimensions": {
    "width_mm": 393.0,
    "depth_mm": 393.0,
    "height_mm": null
  },
  "product_name": "Mica\u00ae Square 393mm Basin",
  "source_pdf": "90011T.pdf"
}
{
  "product_id": "K-12927IN",
  "category": null,
  "dimensions": {
    "width_mm": null,
    "depth_mm": null,
    "height_mm": null
  },
  "product_name": "Complimentary\u2122 Hygiene Spray",
  "source_pdf": "K-12927IN_spec_IN_Kohler_en.pdf"
}
{
  "product_id": "K-1381T-S",
  "category": "Toilet",
  "dimensions": {
    "width_mm": null,
    "depth_mm": null,
    "height_mm": 390.0
  },
  "product_name": "Veil\u2122 One-piece elongated toilet with skirted trapway, dual-flush",
  "source_pdf": "K-1381T-S_spec_IN_Kohler_en.pdf"
}

In [20]:
# Cell 20 — Category summary

category_summary = list(
    products_collection.aggregate([
        {
            "$group": {
                "_id": "$category",
                "count": {"$sum": 1}
            }
        },
        {
            "$sort": {
                "count": -1
            }
        }
    ])
)

print("Products by category:")

for item in category_summary:
    print(
        f"{item['_id']}: {item['count']}"
    )

Products by category:
Faucet: 14
Bathroom sink: 5
Toilet: 5
None: 4
Sink: 2
Toilet Seat: 1
Vessel: 1
BASINS / COUNTERTOP: 1
Bathroom Sink: 1
Faucet Trim: 1
Bathroom sink faucet: 1

In [21]:
# Cell 21 — Find products with missing dimensions

missing_dimension_documents = list(
    products_collection.find(
        {
            "$or": [
                {"dimensions.width_mm": None},
                {"dimensions.depth_mm": None},
                {"dimensions.height_mm": None}
            ]
        },
        {
            "_id": 0,
            "product_id": 1,
            "product_name": 1,
            "category": 1,
            "dimensions": 1,
            "source_pdf": 1
        }
    )
)

print(
    f"Products with one or more missing dimensions: "
    f"{len(missing_dimension_documents)}"
)

if missing_dimension_documents:
    display(
        pd.DataFrame(missing_dimension_documents)
    )

Products with one or more missing dimensions: 34

,product_id,category,dimensions,product_name,source_pdf
0,1311520-A04-D,BASINS / COUNTERTOP,"{'width_mm': 393.0, 'depth_mm': 393.0, 'height...",Mica® Square 393mm Basin,90011T.pdf
1,K-12927IN,NaN,"{'width_mm': None, 'depth_mm': None, 'height_m...",Complimentary™ Hygiene Spray,K-12927IN_spec_IN_Kohler_en.pdf
2,K-1381T-S,Toilet,"{'width_mm': None, 'depth_mm': None, 'height_m...",Veil™ One-piece elongated toilet with skirted ...,K-1381T-S_spec_IN_Kohler_en.pdf
3,K-17629T-NS,Toilet,"{'width_mm': None, 'depth_mm': None, 'height_m...",Ove™ One-piece round-front toilet with skirted...,K-17629T-NS_spec_IN_Kohler_en.pdf
4,K-17660T-M,Toilet Seat,"{'width_mm': None, 'depth_mm': None, 'height_m...",Ove™ Quiet-Close™ elongated toilet seat,K-17660T-M_spec_IN_Kohler_en.pdf
5,K-1851IN,NaN,"{'width_mm': None, 'depth_mm': None, 'height_m...",Brive Plus,K-1851IN_spec_IN_Kohler_en.pdf
6,K-1853IN,NaN,"{'width_mm': None, 'depth_mm': None, 'height_m...",Brive Plus,K-1853IN_spec_IN_Kohler_en.pdf
7,K-21226IN,Sink,"{'width_mm': 600.0, 'depth_mm': 113.0, 'height...",ModernLife Edge 600 mm rectangular vessel bath...,K-21226IN_spec_IN_Kohler_en.pdf
8,K-2200IN,Sink,"{'width_mm': 413.0, 'depth_mm': None, 'height_...",Conical Bell™,K-2200IN_spec_IN_Kohler_en.pdf
9,K-23486IN-4ND,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...","Parallel™ Wall-mount bathroom sink faucet, 9.0...",K-23486IN-4ND_spec_IN_Kohler_en.pdf
10,K-23966IN-4ND,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...",KOHLER VIVE® Single-handle bathroom sink fauce...,K-23966IN-4ND_spec_IN_Kohler_en.pdf
11,K-23967IN-4ND,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...",KOHLER VIVE® Tall single-handle bathroom sink ...,K-23967IN-4ND_spec_IN_Kohler_en.pdf
12,K-25316IN,Bathroom sink,"{'width_mm': 537.0, 'depth_mm': None, 'height_...",Span™ 537 mm rectangular vessel bathroom sink ...,K-25316IN_spec_IN_Kohler_en.pdf
13,K-2661IN,Bathroom sink,"{'width_mm': 413.0, 'depth_mm': 413.0, 'height...",Vox™ 413 mm square vessel bathroom sink,K-2661IN_spec_IN_Kohler_en.pdf
14,K-27477IN-4ND,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...","Fore Tri® Single-handle bathroom sink faucet, ...",K-27477IN-4ND_spec_IN_Kohler_en.pdf
15,K-27480IN-4ND,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...",Fore Line™ Tall single-handle bathroom sink fa...,K-27480IN-4ND_spec_IN_Kohler_en.pdf
16,K-27485IN-4,Faucet,"{'width_mm': None, 'depth_mm': 96.0, 'height_m...","Fore Line™ Single-handle bathroom sink faucet,...",K-27485IN-4_spec_IN_Kohler_en.pdf
17,K-28529IN,Toilet,"{'width_mm': None, 'depth_mm': None, 'height_m...","Leap™ One-piece round-front smart toilet, dual...",K-28529IN_spec_IN_Kohler_en.pdf
18,K-28784IN,Bathroom Sink,"{'width_mm': None, 'depth_mm': None, 'height_m...",KOHLER VIVE® 552 mm rectangular vessel bathroo...,K-28784IN_spec_IN_Kohler_en.pdf
19,K-33123IN-HC,Toilet,"{'width_mm': None, 'depth_mm': None, 'height_m...",KOHLER VIVE Hidden cord one-piece round-front ...,K-33123IN-HC_spec_IN_Kohler_en.pdf
20,K-3983IN-S,Toilet,"{'width_mm': None, 'depth_mm': None, 'height_m...",Reach™ One-piece round-front toilet with skirt...,K-3983IN-S_spec_IN_Kohler_en.pdf
21,K-5373IN,Bathroom sink,"{'width_mm': None, 'depth_mm': None, 'height_m...",Forefront™ 580 mm rectangular vessel bathroom ...,K-5373IN_spec_IN_Kohler_en.pdf
22,K-5684IN-4ND,Faucet Trim,"{'width_mm': None, 'depth_mm': None, 'height_m...","Aleo+™ Wall-mount bathroom sink faucet trim, 9...",K-5684IN-4ND_spec_IN_Kohler_en.pdf
23,K-72298IN-4ND,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...","Aleo® Tall single-handle bathroom sink faucet,...",K-72298IN-4ND_spec_IN_Kohler_en.pdf
24,K-72337IN-4ND,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...",Aleo+™ Tall single-handle bathroom sink faucet...,K-72337IN-4ND_spec_IN_Kohler_en.pdf
25,K-75374IN-1,Bathroom sink,"{'width_mm': 460.0, 'depth_mm': 460.0, 'height...",Forefront™ 460 mm square vessel bathroom sink ...,K-75374IN-1_spec_IN_Kohler_en.pdf
26,K-75375IN,Bathroom sink,"{'width_mm': None, 'depth_mm': None, 'height_m...",Forefront™ 890 mm rectangular vessel bathroom ...,K-75375IN_spec_IN_Kohler_en.pdf
27,K-75377IN-4,Bathroom sink faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...","July™ Single-handle bathroom sink faucet, cold...",K-75377IN-4_spec_IN_Kohler_en.pdf
28,K-77364IN,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...","Health faucet, 8.5 lpm",K-77364IN_spec_IN_Kohler_en.pdf
29,K-97258IN-ZZ,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...","Elate™ Single-function health faucet, 8.5 lpm",K-97258IN-ZZ_spec_IN_Kohler_en.pdf
30,K-97258IN,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...","Elate™ Single-function health faucet, 8.5 lpm",K-97258IN_spec_IN_Kohler_en.pdf
31,K-97347T-4,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...",Avid™ Tall Single-handle bathroom sink faucet,K-97347T-4_spec_GPS_Kohler_en.pdf
32,K-98100IN-ZZ,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...","Beam™ Health faucet, 10 lpm",K-98100IN-ZZ_spec_IN_Kohler_en.pdf
33,K-98100IN,Faucet,"{'width_mm': None, 'depth_mm': None, 'height_m...","Cuff™ Single-function health faucet, 11.5 lpm",K-98100IN_spec_IN_Kohler_en.pdf